"""The 14 built-in themes shipped with ForgeCLI."""
from __future__ import annotations

from typing import Dict

from ..ui.theme import Theme

BUILTIN_THEMES: Dict[str, Theme] = {
    "Dark": Theme(
        name="Dark",
        description="Neutral dark mode. Soft greys with a cyan accent.",
        style="dark",
        bg="black",
        fg="white",
        primary="cyan",
        secondary="bright_cyan",
        success="green",
        warning="yellow",
        danger="red",
        info="blue",
        muted="bright_black",
        border="cyan",
        gradient=["cyan", "white"],
    ),
    "Green Hacker": Theme(
        name="Green Hacker",
        description="Matrix-flavoured green on black.",
        style="dark",
        bg="black",
        fg="green",
        primary="green",
        secondary="bright_green",
        success="bright_green",
        warning="yellow",
        danger="red",
        info="cyan",
        muted="green",
        border="green",
        gradient=["green", "bright_green", "green"],
    ),
    "Blue Neon": Theme(
        name="Blue Neon",
        description="Electric neon blue with magenta highlights.",
        style="dark",
        bg="black",
        fg="white",
        primary="dodger_blue1",
        secondary="deep_pink1",
        success="green",
        warning="yellow",
        danger="red",
        info="cyan",
        muted="bright_black",
        border="dodger_blue1",
        gradient=["dodger_blue1", "deep_pink1", "dodger_blue1"],
    ),
    "Purple": Theme(
        name="Purple",
        description="Royal purples with violet gradients.",
        style="dark",
        bg="black",
        fg="white",
        primary="purple",
        secondary="violet",
        success="green",
        warning="yellow",
        danger="red",
        info="cyan",
        muted="bright_black",
        border="purple",
        gradient=["purple", "violet", "deep_pink1"],
    ),
    "Red": Theme(
        name="Red",
        description="Aggressive red on charcoal.",
        style="dark",
        bg="black",
        fg="white",
        primary="red",
        secondary="bright_red",
        success="green",
        warning="yellow",
        danger="bright_red",
        info="cyan",
        muted="bright_black",
        border="red",
        gradient=["red", "bright_red", "orange1"],
    ),
    "Amber": Theme(
        name="Amber",
        description="Warm amber CRT terminal look.",
        style="dark",
        bg="black",
        fg="bright_yellow",
        primary="dark_orange",
        secondary="yellow",
        success="green",
        warning="yellow",
        danger="red",
        info="cyan",
        muted="yellow",
        border="dark_orange",
        gradient=["dark_orange", "yellow", "dark_orange"],
    ),
    "Catppuccin": Theme(
        name="Catppuccin",
        description="Catppuccin Mocha-inspired palette.",
        style="dark",
        bg="black",
        fg="#cdd6f4",
        primary="#89b4fa",
        secondary="#cba6f7",
        success="#a6e3a1",
        warning="#f9e2af",
        danger="#f38ba8",
        info="#94e2d5",
        muted="#6c7086",
        border="#89b4fa",
        gradient=["#89b4fa", "#cba6f7", "#f5c2e7"],
    ),
    "Tokyo Night": Theme(
        name="Tokyo Night",
        description="Tokyo Night palette, soft blues with hot pink accents.",
        style="dark",
        bg="black",
        fg="#c0caf5",
        primary="#7aa2f7",
        secondary="#bb9af7",
        success="#9ece6a",
        warning="#e0af68",
        danger="#f7768e",
        info="#7dcfff",
        muted="#565f89",
        border="#7aa2f7",
        gradient=["#7aa2f7", "#bb9af7", "#7dcfff"],
    ),
    "Nord": Theme(
        name="Nord",
        description="Polar Nord palette with frosted blues.",
        style="dark",
        bg="black",
        fg="#d8dee9",
        primary="#88c0d0",
        secondary="#81a1c1",
        success="#a3be8c",
        warning="#ebcb8b",
        danger="#bf616a",
        info="#5e81ac",
        muted="#4c566a",
        border="#88c0d0",
        gradient=["#88c0d0", "#81a1c1", "#5e81ac"],
    ),
    "Dracula": Theme(
        name="Dracula",
        description="Dracula palette, vibrant purples and greens.",
        style="dark",
        bg="black",
        fg="#f8f8f2",
        primary="#bd93f9",
        secondary="#ff79c6",
        success="#50fa7b",
        warning="#f1fa8c",
        danger="#ff5555",
        info="#8be9fd",
        muted="#6272a4",
        border="#bd93f9",
        gradient=["#bd93f9", "#ff79c6", "#8be9fd"],
    ),
    "Gruvbox": Theme(
        name="Gruvbox",
        description="Warm retro Gruvbox colors.",
        style="dark",
        bg="black",
        fg="#ebdbb2",
        primary="#fabd2f",
        secondary="#fe8019",
        success="#b8bb26",
        warning="#fabd2f",
        danger="#fb4934",
        info="#83a598",
        muted="#928374",
        border="#fabd2f",
        gradient=["#fabd2f", "#fe8019", "#fb4934"],
    ),
    "Matrix": Theme(
        name="Matrix",
        description="Pure matrix-green code rain feel.",
        style="dark",
        bg="black",
        fg="green",
        primary="green",
        secondary="bright_green",
        success="bright_green",
        warning="yellow",
        danger="bright_red",
        info="green",
        muted="green",
        border="green",
        gradient=["green", "white", "green"],
    ),
    "Cyberpunk": Theme(
        name="Cyberpunk",
        description="Hot magenta on neon cyan. Default ForgeCLI theme.",
        style="dark",
        bg="black",
        fg="white",
        primary="#00fff5",
        secondary="#ff00aa",
        success="#00ff88",
        warning="#ffd000",
        danger="#ff3366",
        info="#00aaff",
        muted="bright_black",
        border="#00fff5",
        gradient=["#00fff5", "#ff00aa", "#00fff5"],
    ),
    "Light": Theme(
        name="Light",
        description="Bright theme for daytime use.",
        style="light",
        bg="white",
        fg="black",
        primary="blue",
        secondary="purple",
        success="green",
        warning="yellow3",
        danger="red",
        info="cyan3",
        muted="grey70",
        border="blue",
        gradient=["blue", "purple"],
    ),
}


def get_builtin_theme(name: str) -> Theme:
    """Look up a built-in theme by name (case-insensitive)."""
    key = name.lower()
    for tname, theme in BUILTIN_THEMES.items():
        if tname.lower() == key:
            return theme
    raise KeyError(f"No built-in theme named {name!r}")


__all__ = ["BUILTIN_THEMES", "get_builtin_theme"]