#!/data/data/com.termux/files/usr/bin/bash
# ForgeCLI — 1-click Termux installer.
#
#   Run from anywhere:
#       curl -fsSL https://raw.githubusercontent.com/cyberkallan/forgecli/main/install-termux.sh | bash
#
#   Or, after cloning:
#       cd forgecli && ./install-termux.sh
#
# The script is idempotent: re-running it just updates deps and re-installs
# the launcher. It never deletes your generated tools or profiles.
set -euo pipefail

CYAN="\033[1;36m"; GREEN="\033[1;32m"; YELLOW="\033[1;33m"; RED="\033[1;31m"; RESET="\033[0m"
REPO_URL="https://github.com/cyberkallan/forgecli.git"
DEST="${FORGECLI_HOME:-$HOME/forgecli}"

banner() {
    printf "%b" "${CYAN}"
    cat <<'EOF'
╔══════════════════════════════════════════════════════════════════╗
║   ____                       _____ _      ____ _      ___       ║
║  |  _ \ _ __ __ _  __ _  ___ / ____| |    / ___| |    |_ _|      ║
║  | | | | '__/ _` |/ _` |/ _ \ |  _| |   | |   | |     | |       ║
║  | |_| | | | (_| | (_| |  __/ |_| | |___| |___| |___  | |       ║
║  |____/|_|  \__,_|\__, |\___|\____|_____|\____|_____|___|       ║
║                   |___/    ForgeCLI — Termux Installer          ║
╚══════════════════════════════════════════════════════════════════╝
EOF
    printf "%b" "${RESET}\n"
}

die() { printf "%b[!] %s%b\n" "$RED" "$1" "$RESET" >&2; exit 1; }
step() { printf "\n%b==>%b %s\n" "$YELLOW" "$RESET" "$1"; }

# --- Termux check --------------------------------------------------------
if [ -z "${PREFIX:-}" ] || [ "${PREFIX:-}" != "/data/data/com.termux/files/usr" ]; then
    die "This installer is for Termux only. On Linux/macOS use: pip install -e ."
fi

banner

# --- Locate or clone the project ----------------------------------------
# When piped (`curl | bash`), $0 has no directory, so we always clone to $DEST.
SCRIPT_DIR="$(cd "$(dirname "$0")" 2>/dev/null && pwd 2>/dev/null || echo "")"
if [ -n "$SCRIPT_DIR" ] && [ -f "$SCRIPT_DIR/forgecli/__init__.py" ]; then
    PROJECT_ROOT="$SCRIPT_DIR"
    step "Running from existing checkout: $PROJECT_ROOT"
else
    PROJECT_ROOT="$DEST"
    if [ -d "$PROJECT_ROOT/.git" ]; then
        step "Updating existing clone at $PROJECT_ROOT"
        git -C "$PROJECT_ROOT" pull --ff-only || true
    else
        step "Cloning ForgeCLI into $PROJECT_ROOT"
        rm -rf "$PROJECT_ROOT"
        git clone --depth 1 "$REPO_URL" "$PROJECT_ROOT"
    fi
fi
cd "$PROJECT_ROOT"

# --- System packages ----------------------------------------------------
step "Installing system packages (python, git, build deps)"
pkg update -y || true
pkg install -y python git clang libffi openssl || \
    die "pkg install failed. Run 'pkg update' manually and retry."

# --- Python deps --------------------------------------------------------
step "Upgrading pip and installing Python dependencies"
python -m pip install --upgrade pip
python -m pip install -r requirements.txt || \
    die "pip install failed. Try: pip install -r requirements.txt --no-cache-dir"

# --- Make scripts executable --------------------------------------------
step "Making scripts executable (chmod +x)"
for f in *.py *.sh; do
    [ -f "$f" ] && chmod +x "$f" && printf "  +x %s\n" "$f"
done

# --- Global launcher ----------------------------------------------------
step "Installing 'forgecli' command to $PREFIX/bin"
cat > "$PREFIX/bin/forgecli" <<LAUNCHER
#!/data/data/com.termux/files/usr/bin/bash
# Auto-generated by install-termux.sh — locates the project and runs it.
export PYTHONIOENCODING=utf-8
export PYTHONUTF8=1
ROOT="$PROJECT_ROOT"
if [ ! -f "\$ROOT/forgecli/__init__.py" ] && [ -f "$HOME/forgecli/forgecli/__init__.py" ]; then
    ROOT="$HOME/forgecli"
fi
cd "\$ROOT" 2>/dev/null || cd "$HOME"
exec python -m forgecli "\$@"
LAUNCHER
chmod +x "$PREFIX/bin/forgecli"

# --- Done ---------------------------------------------------------------
printf "\n%b✔ ForgeCLI installed.%b\n" "$GREEN" "$RESET"
printf "  Project: %s\n" "$PROJECT_ROOT"
printf "  Run it:  %bforgecli%b   (from anywhere in Termux)\n" "$CYAN" "$RESET"
printf "  Update:  %bgit -C %s pull && pip install -r requirements.txt%b\n" "$CYAN" "$PROJECT_ROOT" "$RESET"
exit 0