#!/data/data/com.termux/files/usr/bin/bash
# ForgeCLI — Termux installer
# Usage:  ./install-termux.sh
set -e

CYAN="\033[1;36m"
GREEN="\033[1;32m"
YELLOW="\033[1;33m"
RESET="\033[0m"

banner() {
    printf "%b" "${CYAN}"
    cat <<'EOF'
╔══════════════════════════════════════════════════════════════════╗
║   ____                       _____ _      ____ _      ___       ║
║  |  _ \ _ __ __ _  __ _  ___ / ____| |    / ___| |    |_ _|      ║
║  | | | | '__/ _` |/ _` |/ _ \ |  _| |   | |   | |     | |       ║
║  | |_| | | | (_| | (_| |  __/ |_| | |___| |___| |___  | |       ║
║  |____/|_|  \__,_|\__, |\___|\____|_____|\____|_____|___|       ║
║                   |___/    ForgeCLI — Termux Installer          ║
╚══════════════════════════════════════════════════════════════════╝
EOF
    printf "%b" "${RESET}\n"
}

banner

# 1. System packages ------------------------------------------------------
printf "%b[1/4]%b Updating Termux and installing system deps…\n" "$YELLOW" "$RESET"
pkg update -y && pkg upgrade -y
pkg install -y python git clang libffi openssl

# 2. Python deps ----------------------------------------------------------
printf "%b[2/4]%b Upgrading pip and installing Python deps…\n" "$YELLOW" "$RESET"
python -m pip install --upgrade pip
python -m pip install -r requirements.txt

# 3. Make scripts executable ---------------------------------------------
printf "%b[3/4]%b Making scripts executable (chmod +x)…\n" "$YELLOW" "$RESET"
chmod +x install-termux.sh forgecli.py forge 2>/dev/null || true
# Anything else at the repo root that looks like a script:
for f in *.sh *.py; do
    [ -f "$f" ] && chmod +x "$f"
done

# 4. Optional: install as a global command -------------------------------
if [ -w "$PREFIX/bin" ]; then
    printf "%b[4/4]%b Installing 'forgecli' to %s/bin …\n" "$YELLOW" "$RESET" "$PREFIX"
    cat > "$PREFIX/bin/forgecli" <<'LAUNCHER'
#!/data/data/com.termux/files/usr/bin/bash
# Auto-generated by install-termux.sh
HERE="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$HERE/.." && pwd 2>/dev/null || echo "$HOME/forgecli")"
if [ -f "$PROJECT_ROOT/forgecli/__init__.py" ]; then
    cd "$PROJECT_ROOT"
    exec python -m forgecli "$@"
elif [ -f "$HOME/forgecli/forgecli/__init__.py" ]; then
    cd "$HOME/forgecli"
    exec python -m forgecli "$@"
else
    echo "forgecli: could not locate the project directory." >&2
    exit 1
fi
LAUNCHER
    chmod +x "$PREFIX/bin/forgecli"
else
    printf "%b[4/4]%b PREFIX/bin not writable — skipping global install.\n" "$YELLOW" "$RESET"
fi

printf "\n%b✔ Done.%b Launch with:  forgecli    or    python -m forgecli\n" "$GREEN" "$RESET"