"""Banner rendering for {{PROJECT_NAME}}."""
from __future__ import annotations

from typing import Optional

import pyfiglet
from rich.console import Console
from rich.panel import Panel
from rich.text import Text


FONT = "{{ASCII_FONT}}"
LOGO_TEXT = "{{LOGO_TEXT}}"


def ascii_art(text: str, font: str = FONT) -> Text:
    try:
        raw = pyfiglet.figlet_format(text, font=font)
    except Exception:
        raw = pyfiglet.figlet_format(text, font="standard")
    return Text(raw.rstrip("\n"))


def show_banner(console: Console, theme, *, socials: Optional[dict] = None,
                version: str = "", status: str = "Ready") -> None:
    art = ascii_art(LOGO_TEXT)
    body = Text()
    body.append_text(art)
    if version:
        body.append("\n  ")
        body.append(f"v{version}", style=theme.secondary)
        if status:
            body.append("  •  ", style=theme.muted)
            body.append(status, style=theme.success)
    if socials:
        body.append("\n")
        for label, url in socials.items():
            if not url:
                continue
            body.append("  ▸ ", style=theme.muted)
            body.append(f"{label}: ", style=theme.secondary)
            body.append(url, style=theme.primary)
            body.append("\n")

    panel = Panel(
        body,
        border_style=theme.border,
        title=f"[{theme.primary}]◆[/] [{theme.secondary}]{LOGO_TEXT}[/]",
        subtitle=f"[{theme.muted}]Generated by ForgeCLI[/]",
        padding=(1, 2),
    )
    console.print(panel)
