# Changelog

All notable changes to {{PROJECT_NAME}} are documented here.
The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.1.0/).

## [{{VERSION}}] - {{DATE}}

### Added
- Initial release generated by ForgeCLI.
- {{SUBCATEGORY}} command set under the {{CATEGORY}} category.
- Themed banner, system info dashboard, and update checker.

### Security
- Encryption uses PBKDF2-HMAC-SHA256 (200k iterations) with an HMAC-SHA256
  integrity tag. Suitable for obfuscating secrets; not a vetted standard.