# Contributing to {{PROJECT_NAME}}

Thanks for your interest in contributing! This project was generated by
[ForgeCLI](https://github.com/cyberkallan/forgecli), so its structure is
uniform across every tool in the ecosystem.

## Development setup

```bash
git clone {{GITHUB}}
cd {{SLUG}}
python -m venv .venv && source .venv/bin/activate
pip install -r requirements.txt
pip install pytest rich pyfiglet questionary
pip install -e .
```

## Project layout

```
{{SLUG}}/
├── main.py          entry point & menu loop
├── banner.py        ASCII banner rendering
├── ui.py            prompts + animated helpers
├── utils.py         system info, network checks
├── theme.py         runtime theme loading
├── installer.py     auto-installer for missing deps
├── updater.py       PyPI update checker
├── commands.py      all the command implementations
├── config.json      your branding snapshot
├── theme.json       resolved theme palette
├── branding.json    Branding dataclass dump
├── plugins/         drop-in extensions
├── examples/        CLI usage examples
└── tests/           pytest suite
```

## Adding a new command

1. Open `commands.py`.
2. Add a function `def cmd_xxx(ctx): ...` that uses `ctx["ask"]`, `ctx["console"]`,
   `ctx["theme"]`, etc.
3. Register it under the right category / subcategory in the `COMMANDS` dict.

## Adding a plugin

Drop a `.py` file under `plugins/` with a `register(ctx)` function returning
`[(label, callable)]`. No rebuild required — the loader picks them up on next
start.

## Style guide

- Python 3.9+ — keep compatibility with the bundled stdlib.
- Prefer stdlib over dependencies. If a non-stdlib dep is genuinely needed,
  add it to `requirements.txt` and document it.
- Real implementations only — no fake or placeholder commands.

## Submitting a PR

1. Fork the repo.
2. Create a feature branch (`git checkout -b feature/my-thing`).
3. Add tests in `tests/`.
4. Run `pytest` and ensure everything passes.
5. Open a PR.

## Code of conduct

Be kind, be helpful, and assume good faith. Harassment of any kind is not
tolerated.