#!/usr/bin/env python3
# {{PROJECT_NAME}} entry point - generated by ForgeCLI.
"""{{PROJECT_NAME}} - {{TAGLINE}}"""
from __future__ import annotations

import os
import sys


def _force_utf8_io() -> None:
    """Force UTF-8 on stdout/stderr so ``rich`` can print any character.

    On Windows, the default console codepage is often cp1252 or similar,
    which causes ``UnicodeEncodeError`` when rendering box-drawing, emoji,
    or any non-Latin glyphs. This reconfigures the streams in place when
    possible and falls back to ``PYTHONIOENCODING`` for the rare cases
    where the handles aren't reconfigurable (e.g. a non-standard wrapper).
    """
    if sys.platform.startswith("win"):
        os.environ.setdefault("PYTHONIOENCODING", "utf-8")
        for stream_name in ("stdout", "stderr"):
            stream = getattr(sys, stream_name, None)
            reconfigure = getattr(stream, "reconfigure", None)
            if callable(reconfigure):
                try:
                    reconfigure(encoding="utf-8", errors="replace")
                except Exception:
                    # If we can't reconfigure, the env var above still nudges
                    # child interpreters and ``io`` wrappers toward UTF-8.
                    pass


_force_utf8_io()

# Auto-install runtime dependencies the first time we run.
from installer import ensure_runtime_dependencies  # noqa: E402

ensure_runtime_dependencies([
    "rich>=13.7.0",
    "pyfiglet>=1.0.2",
    "questionary>=2.0.1",
])

from rich.console import Console

from theme import load_theme, get_builtin_theme
from banner import show_banner
from ui import info_table, make_ctx, select_menu, run_startup_animation
from utils import collect_system_info
from updater import check_for_update
from commands import commands_for


def _load_plugins(ctx) -> list:
    """Auto-discover drop-in plugins under ./plugins/*.py.

    Each plugin may expose ``register(ctx) -> [(label, callable), ...]`` which
    returns commands to merge into the menu. Plugins that fail to load are
    reported but never crash the tool.
    """
    import importlib.util
    import traceback
    plugins_dir = os.path.join(os.path.dirname(__file__), "plugins")
    merged = []
    if not os.path.isdir(plugins_dir):
        return merged
    for path in sorted(os.listdir(plugins_dir)):
        if not path.endswith(".py") or path.startswith("_"):
            continue
        name = path[:-3]
        try:
            spec = importlib.util.spec_from_file_location(f"plugin_{name}",
                                                          os.path.join(plugins_dir, path))
            mod = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(mod)
            register = getattr(mod, "register", None)
            if callable(register):
                extra = register(ctx) or []
                merged.extend(extra)
        except Exception:  # a broken plugin must not kill the tool
            print(f"[plugin {name}] failed to load:")
            traceback.print_exc()
    return merged


PROJECT_NAME = "{{PROJECT_NAME}}"
COMMAND_NAME = "{{COMMAND_NAME}}"
VERSION = "{{VERSION}}"
CATEGORY = "{{CATEGORY}}"
SUBCATEGORY = "{{SUBCATEGORY}}"
SOCIALS = {
    "GitHub": "{{GITHUB}}",
    "Instagram": "{{INSTAGRAM}}",
    "Website": "{{WEBSITE}}",
}


def main() -> int:
    console = Console()
    chosen = load_theme()
    theme = chosen or get_builtin_theme("{{THEME_NAME}}")

    run_startup_animation(console, theme, animation="{{STARTUP_ANIMATION}}")
    show_banner(console, theme, socials=SOCIALS, version=VERSION)
    info_table(console, theme, collect_system_info())

    ctx = make_ctx(console, theme, version=VERSION, category=CATEGORY,
                   subcategory=SUBCATEGORY)

    if {{AUTO_UPDATE}}:
        try:
            check_for_update(PROJECT_NAME, VERSION, console, theme)
        except Exception:  # never let updater block the tool
            pass

    commands = commands_for(CATEGORY, SUBCATEGORY)
    commands = list(commands) + _load_plugins(ctx)

    while True:
        if not commands:
            console.print(f"[{theme.warning}]No commands registered.[/]")
            return 0
        labels = [name for name, _ in commands] + ["Help", "About", "Update check", "Exit"]
        try:
            choice = select_menu("Choose a command", labels, theme=theme)
        except (KeyboardInterrupt, EOFError):
            console.print(f"[{theme.muted}]Goodbye.[/]")
            return 0

        if not choice:
            continue

        if choice == "Exit":
            console.print(f"[{theme.primary}]Bye.[/]")
            return 0
        if choice == "Help":
            console.print(f"[{theme.info}]Use the arrow keys, Enter to confirm.[/]")
            continue
        if choice == "About":
            console.print(f"[{theme.secondary}]{PROJECT_NAME}[/] v{VERSION}\n{{FOOTER_TEXT}}")
            continue
        if choice == "Update check":
            try:
                check_for_update(PROJECT_NAME, VERSION, console, theme, force=True)
            except Exception as exc:
                console.print(f"[{theme.warning}]Update check failed: {exc}[/]")
            continue

        for name, fn in commands:
            if name == choice:
                try:
                    fn(ctx)
                except KeyboardInterrupt:
                    console.print("[yellow]Cancelled.[/]")
                except Exception as exc:
                    console.print(f"[{theme.danger}]{name} failed:[/] {exc}")
                break


if __name__ == "__main__":
    sys.exit(main())
