#!/usr/bin/env python3
# {{PROJECT_NAME}} entry point - generated by ForgeCLI.
"""{{PROJECT_NAME}} - {{TAGLINE}}"""
from __future__ import annotations

import os
import sys

# Auto-install runtime dependencies the first time we run.
from installer import ensure_runtime_dependencies  # noqa: E402

ensure_runtime_dependencies([
    "rich>=13.7.0",
    "pyfiglet>=1.0.2",
    "questionary>=2.0.1",
])

from rich.console import Console
import questionary

from theme import load_theme, get_builtin_theme
from banner import show_banner
from ui import info_table, make_ctx, render_menu, run_startup_animation
from utils import collect_system_info
from updater import check_for_update
from commands import commands_for


PROJECT_NAME = "{{PROJECT_NAME}}"
COMMAND_NAME = "{{COMMAND_NAME}}"
VERSION = "{{VERSION}}"
CATEGORY = "{{CATEGORY}}"
SUBCATEGORY = "{{SUBCATEGORY}}"
SOCIALS = {
    "GitHub": "{{GITHUB}}",
    "Instagram": "{{INSTAGRAM}}",
    "Website": "{{WEBSITE}}",
}


def main() -> int:
    console = Console()
    chosen = load_theme()
    theme = chosen or get_builtin_theme("{{THEME_NAME}}")

    run_startup_animation(console, theme, animation="{{STARTUP_ANIMATION}}")
    show_banner(console, theme, socials=SOCIALS, version=VERSION)
    info_table(console, theme, collect_system_info())

    ctx = make_ctx(console, theme, version=VERSION, category=CATEGORY,
                   subcategory=SUBCATEGORY)

    if {{AUTO_UPDATE}}:
        try:
            check_for_update(PROJECT_NAME, VERSION, console, theme)
        except Exception:  # never let updater block the tool
            pass

    commands = commands_for(CATEGORY, SUBCATEGORY)

    while True:
        if not commands:
            console.print(f"[{theme.warning}]No commands registered.[/]")
            return 0
        labels = [name for name, _ in commands] + ["Help", "About", "Update check", "Exit"]
        try:
            rendered = render_menu(theme)
            choice = questionary.select(
                "Choose a command",
                choices=labels,
            ).ask()
        except (KeyboardInterrupt, EOFError):
            console.print(f"[{theme.muted}]Goodbye.[/]")
            return 0

        if not choice:
            continue

        if choice == "Exit":
            console.print(f"[{theme.primary}]Bye.[/]")
            return 0
        if choice == "Help":
            console.print(f"[{theme.info}]Use the arrow keys, Enter to confirm.[/]")
            continue
        if choice == "About":
            console.print(f"[{theme.secondary}]{PROJECT_NAME}[/] v{VERSION}\n{{FOOTER_TEXT}}")
            continue
        if choice == "Update check":
            try:
                check_for_update(PROJECT_NAME, VERSION, console, theme, force=True)
            except Exception as exc:
                console.print(f"[{theme.warning}]Update check failed: {exc}[/]")
            continue

        for name, fn in commands:
            if name == choice:
                try:
                    fn(ctx)
                except KeyboardInterrupt:
                    console.print("[yellow]Cancelled.[/]")
                except Exception as exc:
                    console.print(f"[{theme.danger}]{name} failed:[/] {exc}")
                break


if __name__ == "__main__":
    sys.exit(main())
